// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package decls

import (
	canondecls "cel.dev/cel-go/common/decls"
	"cel.dev/cel-go/common/functions"
	"cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/ref"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

// Type aliases
type (
	FunctionDecl      = canondecls.FunctionDecl
	FunctionOpt       = canondecls.FunctionOpt
	FunctionSubsetter = canondecls.FunctionSubsetter
	OverloadDecl      = canondecls.OverloadDecl
	OverloadOpt       = canondecls.OverloadOpt
	OverloadSelector  = canondecls.OverloadSelector
	VariableDecl      = canondecls.VariableDecl
)

// Functions

func AsyncBinding(fn functions.BlockingAsyncOp) OverloadOpt {
	return canondecls.AsyncBinding(fn)
}

func BinaryBinding(binding functions.BinaryOp) OverloadOpt {
	return canondecls.BinaryBinding(binding)
}

func DisableDeclaration(value bool) FunctionOpt {
	return canondecls.DisableDeclaration(value)
}

func DisableTypeGuards(value bool) FunctionOpt {
	return canondecls.DisableTypeGuards(value)
}

func ExcludeOverloads(overloadIDs ...string) OverloadSelector {
	return canondecls.ExcludeOverloads(overloadIDs...)
}

func FunctionBinding(binding functions.FunctionOp) OverloadOpt {
	return canondecls.FunctionBinding(binding)
}

func FunctionDeclToExprDecl(f *FunctionDecl) (*exprpb.Decl, error) {
	return canondecls.FunctionDeclToExprDecl(f)
}

func FunctionDocs(docs ...string) FunctionOpt {
	return canondecls.FunctionDocs(docs...)
}

func IncludeOverloads(overloadIDs ...string) OverloadSelector {
	return canondecls.IncludeOverloads(overloadIDs...)
}

func LateFunctionBinding() OverloadOpt {
	return canondecls.LateFunctionBinding()
}

func MaybeNoSuchOverload(funcName string, args ...ref.Val) ref.Val {
	return canondecls.MaybeNoSuchOverload(funcName, args...)
}

func MemberOverload(overloadID string,
	args []*types.Type, resultType *types.Type,
	opts ...OverloadOpt) FunctionOpt {
	return canondecls.MemberOverload(overloadID, args, resultType, opts...)
}

func NewConstant(name string, t *types.Type, v ref.Val) *VariableDecl {
	return canondecls.NewConstant(name, t, v)
}

func NewFunction(name string, opts ...FunctionOpt) (*FunctionDecl, error) {
	return canondecls.NewFunction(name, opts...)
}

func NewVariable(name string, t *types.Type) *VariableDecl {
	return canondecls.NewVariable(name, t)
}

func NewVariableWithDoc(name string, t *types.Type, doc string) *VariableDecl {
	return canondecls.NewVariableWithDoc(name, t, doc)
}

func Overload(overloadID string,
	args []*types.Type, resultType *types.Type,
	opts ...OverloadOpt) FunctionOpt {
	return canondecls.Overload(overloadID, args, resultType, opts...)
}

func OverloadExamples(examples ...string) OverloadOpt {
	return canondecls.OverloadExamples(examples...)
}

func OverloadIsNonStrict() OverloadOpt {
	return canondecls.OverloadIsNonStrict()
}

func OverloadOperandTrait(trait int) OverloadOpt {
	return canondecls.OverloadOperandTrait(trait)
}

func SingletonAsyncBinding(fn functions.BlockingAsyncOp, traits ...int) FunctionOpt {
	return canondecls.SingletonAsyncBinding(fn, traits...)
}

func SingletonBinaryBinding(fn functions.BinaryOp, traits ...int) FunctionOpt {
	return canondecls.SingletonBinaryBinding(fn, traits...)
}

func SingletonFunctionBinding(fn functions.FunctionOp, traits ...int) FunctionOpt {
	return canondecls.SingletonFunctionBinding(fn, traits...)
}

func SingletonUnaryBinding(fn functions.UnaryOp, traits ...int) FunctionOpt {
	return canondecls.SingletonUnaryBinding(fn, traits...)
}

func TypeVariable(t *types.Type) *VariableDecl {
	return canondecls.TypeVariable(t)
}

func UnaryBinding(binding functions.UnaryOp) OverloadOpt {
	return canondecls.UnaryBinding(binding)
}

func VariableDeclToExprDecl(v *VariableDecl) (*exprpb.Decl, error) {
	return canondecls.VariableDeclToExprDecl(v)
}
