// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package jwt

import (
	"time"

	canoncel "cel.dev/cel-go/cel"
	canonjwt "cel.dev/cel-go/ext/security/jwt"
)

// Type aliases
type (
	Option = canonjwt.Option
	Token  = canonjwt.Token
)

// Functions
func Library(options ...Option) canoncel.EnvOption {
	return canonjwt.Library(options...)
}

func Version(version uint32) Option {
	return canonjwt.Version(version)
}

func ValidateTimes(leeway ...time.Duration) Option {
	return canonjwt.ValidateTimes(leeway...)
}

func Clock(nowFunc func() time.Time) Option {
	return canonjwt.Clock(nowFunc)
}

func ClockLeeway(leeway time.Duration) Option {
	return canonjwt.ClockLeeway(leeway)
}

func NewToken(header, payload map[string]any) (*Token, error) {
	return canonjwt.NewToken(header, payload)
}

func ParseToken(tokenStr string) (*Token, error) {
	return canonjwt.ParseToken(tokenStr)
}
