// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package test

import (
	"cel.dev/cel-go/common/types/ref"
	canontest "cel.dev/cel-go/test"
	"context"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	"time"
)

// Type aliases
type (
	Case         = canontest.Case
	InputContext = canontest.InputContext
	InputValue   = canontest.InputValue
	Output       = canontest.Output
	Section      = canontest.Section
	Suite        = canontest.Suite
	TestExpr     = canontest.TestExpr
)

// Variables
var (
	Conditional           = canontest.Conditional
	DynMap                = canontest.DynMap
	Empty                 = canontest.Empty
	Equality              = canontest.Equality
	Exists                = canontest.Exists
	ExistsWithInput       = canontest.ExistsWithInput
	LogicalAnd            = canontest.LogicalAnd
	LogicalAndMissingType = canontest.LogicalAndMissingType
	LogicalOr             = canontest.LogicalOr
	LogicalOrEquals       = canontest.LogicalOrEquals
	Select                = canontest.Select
	TypeEquality          = canontest.TypeEquality
)

// Functions

func Compare(a string, e string) bool {
	return canontest.Compare(a, e)
}

func DiffMessage(context string, actual interface{}, expected interface{}) string {
	return canontest.DiffMessage(context, actual, expected)
}

func ExprCall(id int64, function string, args ...*exprpb.Expr) *exprpb.Expr {
	return canontest.ExprCall(id, function, args...)
}

func ExprComprehension(id int64,
	iterVar string, iterRange *exprpb.Expr,
	accuVar string, accuInit *exprpb.Expr,
	loopCondition *exprpb.Expr, loopStep *exprpb.Expr,
	resultExpr *exprpb.Expr) *exprpb.Expr {
	return canontest.ExprComprehension(id, iterVar, iterRange, accuVar, accuInit, loopCondition, loopStep, resultExpr)
}

func ExprEntry(id int64, key *exprpb.Expr,
	value *exprpb.Expr) *exprpb.Expr_CreateStruct_Entry {
	return canontest.ExprEntry(id, key, value)
}

func ExprField(id int64, field string,
	value *exprpb.Expr) *exprpb.Expr_CreateStruct_Entry {
	return canontest.ExprField(id, field, value)
}

func ExprIdent(id int64, name string) *exprpb.Expr {
	return canontest.ExprIdent(id, name)
}

func ExprList(id int64, elements ...*exprpb.Expr) *exprpb.Expr {
	return canontest.ExprList(id, elements...)
}

func ExprLiteral(id int64, value any) *exprpb.Expr {
	return canontest.ExprLiteral(id, value)
}

func ExprMap(id int64, entries ...*exprpb.Expr_CreateStruct_Entry) *exprpb.Expr {
	return canontest.ExprMap(id, entries...)
}

func ExprMemberCall(id int64, function string, target *exprpb.Expr, args ...*exprpb.Expr) *exprpb.Expr {
	return canontest.ExprMemberCall(id, function, target, args...)
}

func ExprSelect(id int64, operand *exprpb.Expr, field string) *exprpb.Expr {
	return canontest.ExprSelect(id, operand, field)
}

func ExprType(id int64, messageName string,
	entries ...*exprpb.Expr_CreateStruct_Entry) *exprpb.Expr {
	return canontest.ExprType(id, messageName, entries...)
}

func FakeRPC(timeout time.Duration) func(context.Context, ...ref.Val) ref.Val {
	return canontest.FakeRPC(timeout)
}
