// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package hmac

import (
	"crypto"

	canoncel "cel.dev/cel-go/cel"
	canonhmac "cel.dev/cel-go/ext/security/hmac"
)

// Type aliases
type (
	Option = canonhmac.Option
)

// Functions
func Library(options ...Option) canoncel.EnvOption {
	return canonhmac.Library(options...)
}

func Version(version uint32) Option {
	return canonhmac.Version(version)
}

func MaxPrefixLength(limit int) Option {
	return canonhmac.MaxPrefixLength(limit)
}

func Algorithm(h crypto.Hash, aliases ...string) Option {
	return canonhmac.Algorithm(h, aliases...)
}

func CommonAlgorithms() Option {
	return canonhmac.CommonAlgorithms()
}
