dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - wget
    - pkg-config
before_install:
- wget https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel_0.20.0-linux-x86_64.deb
- sudo dpkg -i bazel_0.20.0-linux-x86_64.deb
script:
- bazel test --test_output=errors ...
deploy:
  provider: gcs
  access_key_id: 577380756900-b1mqjton47h3fj90baqke9bhq75nagh3.apps.googleusercontent.com
  secret_access_key: qkfbetIQCrt6mYiAzCdO4YyL
  bucket: travis-content
  skip_cleanup: true
  on:
    repo: victoriajyang/cel-go
