steps:
        - name: 'gcr.io/cloud-builders/bazel'
          args: ['build']
        - name: 'ubuntu'
          args: ['bash', 't.sh']
          #          args: ['test', '--test_output=errors', '--test_output=all', 'conformance/ct']
        - name: 'ubuntu'
          args: ['bash', 'zip.sh']
artifacts:
        objects:
                location: gs://travis-content
                paths: ['tests.xml']
