steps:
        - name: 'ubuntu'
          args: ['bash', 'conformance/start.sh', '$COMMIT_SHA']
        - name: 'ubuntu'
          args: ['bash', '-c', 'date +%s > _DATE' ]
        - name: 'gcr.io/cloud-builders/gsutil'
          args: ['cp', '-r', '_DATE', 'gs://travis-content']
        - name: 'gcr.io/cloud-builders/bazel'
          args: ['test', '--test_output=all', 'conformance/ct']
          env:
                  - 'ZONEINFO=./common/types/zoneinfo.zip'
        - name: 'ubuntu'
          args: ['bash', 'conformance/zip.sh']
        - name: 'gcr.io/cloud-builders/gsutil'
          entrypoint: sh
          args: ['-c', 'gsutil cp -r $(cat _DATE) gs://travis-content/test-logs/']
