steps:
        - name: 'gcr.io/cloud-builders/bazel'
          args: ['test', '--test_output=errors', '--test_output=all', '...']
        - name: 'gcr.io/cloud-builders/gsutil'
          args: ['cp', './zip_log.sh', 'gs://travis-content']
          #     - name: 'ubuntu'
          #  args: ['bash', './zip_log.sh']
          #artifacts:
          # objects:
          #      location: gs://travis-content
          #      paths: ['./bazel-out']

