steps:
        - name: 'ubuntu'
          args: ['bash', 'start.sh', '$COMMIT_SHA']
        - name: 'ubuntu'
          args: ['bash', '-c', 'date +%s > _DATE' ]
        - name: 'ubuntu'
          args: ['ls']
        - name: 'gcr.io/cloud-builders/gsutil'
          args: ['cp', '-r', '_DATE', 'gs://travis-content']
          #        - name: 'gcr.io/cloud-builders/bazel'
          #   args: ['test', '--test_output=all', 'conformance/ct']
        - name: 'ubuntu'
          args: ['bash', 'zip.sh']
        - name: 'gcr.io/cloud-builders/gsutil'
          args: ['cp', '-r', '[cat gs://travis-content/_DATE]', 'gs://travis-content/test-logs']
