steps:
        - name: 'gcr.io/cloud-builders/bazel'
          args: ['test', '--test_output=errors', '...']
artifacts:
        objects:
                location: gs://travis-content
                paths: ['*.xml']
