steps:
        - name: 'ubuntu'
          args: ['bash', 'conformance/start.sh', '$COMMIT_SHA']
        # Because testgrid uses monotonically increasing, numerical ids as folder names and GCB generates random ids, the timestamp
        # at start is recorded and written to a file, then read at the end to ensure monotonically increasing numbers.
        - name: 'ubuntu'
          args: ['bash', '-c', 'date +%s > _DATE' ]
        - name: 'gcr.io/cloud-builders/gsutil'
          args: ['cp', '-r', '_DATE', 'gs://cel-conformance']
        - name: 'gcr.io/cloud-builders/bazel'
          args: ['test', '--test_output=all', 'conformance/ct_dashboard']
        - name: 'ubuntu'
          args: ['bash', 'conformance/zip.sh']
        - name: 'gcr.io/cloud-builders/gsutil'
          entrypoint: sh
          args: ['-c', 'gsutil cp -r $(cat _DATE) gs://cel-conformance/test-logs/']
