steps:
        - name: 'gcr.io/cloud-builders/bazel'
          #         entrypoint: '/bin/bash'
          #
          args: [ 'bazel test --test_output=errors --test_output=all ...' || true ]
        - name: 'ubuntu'
          args: ['bash', 'zip.sh']
artifacts:
        objects:
                location: gs://travis-content
                paths: ['tests.xml']
