steps:
        - name: 'ubuntu'
          args: ['bash', 'start.sh', '"$COMMIT_SHA"']
        #  args: ['bash', '-c', 'ls']
          #        - name: 'gcr.io/cloud-builders/bazel'
          #  args: ['test', '--test_output=all', 'conformance/ct']
          #  - name: 'ubuntu'
          #  args: ['bash', 'zip.sh']
artifacts:
        objects:
                location: gs://travis-content
                paths: ['build-log.txt']
