steps:
        - name: 'ubuntu'
          args: ['bash', 'date+%s', '>', 'build-log.txt']
          args: ['bash', 'hello284y298462986', '>>', 'build-log.txt']
          #          args: ['bash', 'echo', '"74e2442924889b6864d2ee5084d37e1258602c7d"', '>>', 'build-log.txt']
          #          args: ['bash', 'echo', '"$COMMIT_SHA commit"', '>>', 'build-log.txt']
          #        - name: 'gcr.io/cloud-builders/bazel'
          #  args: ['test', '--test_output=all', 'conformance/ct']
          #  - name: 'ubuntu'
          #  args: ['bash', 'zip.sh']
artifacts:
        objects:
                location: gs://travis-content
                paths: ['tests.xml', 'build-log.txt']
