steps:
        - name: 'gcr.io/cloud-builders/bazel'
          args: ['test', '--test_output=all', '...']
        - name: 'ubuntu'
          args: ['bash', 'zip.sh']
artifacts:
        objects:
                location: gs://travis-content
                paths: ['tests.xml']
