// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package policy

import (
	"cel.dev/cel-go/cel"
	"cel.dev/cel-go/common/ast"
	"cel.dev/cel-go/common/env"
	canonpolicy "cel.dev/cel-go/policy"
)

// Type aliases
type (
	CompileMatchOutputFunc = canonpolicy.CompileMatchOutputFunc
	CompiledMatch          = canonpolicy.CompiledMatch
	CompiledRule           = canonpolicy.CompiledRule
	CompiledVariable       = canonpolicy.CompiledVariable
	CompilerOption         = canonpolicy.CompilerOption
	ComposerOption         = canonpolicy.ComposerOption
	Import                 = canonpolicy.Import
	Match                  = canonpolicy.Match
	MatchCompiler          = canonpolicy.MatchCompiler
	OutputValue            = canonpolicy.OutputValue
	Parser                 = canonpolicy.Parser
	ParserContext          = canonpolicy.ParserContext
	ParserOption           = canonpolicy.ParserOption
	Policy                 = canonpolicy.Policy
	RelativeSource         = canonpolicy.RelativeSource
	Rule                   = canonpolicy.Rule
	RuleComposer           = canonpolicy.RuleComposer
	SemanticType           = canonpolicy.SemanticType
	Source                 = canonpolicy.Source
	TagVisitor             = canonpolicy.TagVisitor
	TestCase               = canonpolicy.TestCase
	TestInput              = canonpolicy.TestInput
	TestSection            = canonpolicy.TestSection
	TestSuite              = canonpolicy.TestSuite
	ValueString            = canonpolicy.ValueString
	Variable               = canonpolicy.Variable
	YAMLHelper             = canonpolicy.YAMLHelper
)

// Functions

func ByteSource(contents []byte, location string) *Source {
	return canonpolicy.ByteSource(contents, location)
}

func Compile(env *cel.Env, p *Policy, opts ...CompilerOption) (*cel.Ast, *cel.Issues) {
	return canonpolicy.Compile(env, p, opts...)
}

func CompileMatchOutput(f CompileMatchOutputFunc) CompilerOption {
	return canonpolicy.CompileMatchOutput(f)
}

func CompileRule(env *cel.Env, p *Policy, opts ...CompilerOption) (*CompiledRule, *cel.Issues) {
	return canonpolicy.CompileRule(env, p, opts...)
}

func CustomTagVisitor(visitor TagVisitor) ParserOption {
	return canonpolicy.CustomTagVisitor(visitor)
}

func DefaultTagVisitor() TagVisitor {
	return canonpolicy.DefaultTagVisitor()
}

func ExpressionUnnestHeight(height int) ComposerOption {
	return canonpolicy.ExpressionUnnestHeight(height)
}

func FromConfig(config *env.Config) cel.EnvOption {
	return canonpolicy.FromConfig(config)
}

func K8sTestTagHandler() TagVisitor {
	return canonpolicy.K8sTestTagHandler()
}

func MaxNestedExpressions(limit int) CompilerOption {
	return canonpolicy.MaxNestedExpressions(limit)
}

func NewImport(exprID int64) *Import {
	return canonpolicy.NewImport(exprID)
}

func NewMatch(exprID int64) *Match {
	return canonpolicy.NewMatch(exprID)
}

func NewParser(opts ...ParserOption) (*Parser, error) {
	return canonpolicy.NewParser(opts...)
}

func NewPolicy(src *Source, info *ast.SourceInfo) *Policy {
	return canonpolicy.NewPolicy(src, info)
}

func NewRule(exprID int64) *Rule {
	return canonpolicy.NewRule(exprID)
}

func NewRuleComposer(env *cel.Env, opts ...ComposerOption) (*RuleComposer, error) {
	return canonpolicy.NewRuleComposer(env, opts...)
}

func NewVariable(exprID int64) *Variable {
	return canonpolicy.NewVariable(exprID)
}

func SimpleVariables() ParserOption {
	return canonpolicy.SimpleVariables()
}

func StringSource(contents, location string) *Source {
	return canonpolicy.StringSource(contents, location)
}
