// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package runes

import (
	canonrunes "cel.dev/cel-go/common/runes"
)

// Type aliases
type (
	Buffer         = canonrunes.Buffer
	SizeLimitError = canonrunes.SizeLimitError
)

// Functions

func NewBuffer(data string) Buffer {
	return canonrunes.NewBuffer(data)
}

func NewBufferAndLineOffsets(data string) (Buffer, []int32) {
	return canonrunes.NewBufferAndLineOffsets(data)
}

func NewBufferAndLineOffsetsWithLimit(data string, limit int) (Buffer, []int32, error) {
	return canonrunes.NewBufferAndLineOffsetsWithLimit(data, limit)
}
