// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package async

import (
	canonasync "cel.dev/cel-go/cel/async"
	"cel.dev/cel-go/common/decls"
	"cel.dev/cel-go/common/functions"
	"time"
)

// Type aliases
type (
	BlockingOp     = canonasync.BlockingOp
	Call           = canonasync.Call
	DrainAction    = canonasync.DrainAction
	DrainStrategy  = canonasync.DrainStrategy
	Observer       = canonasync.Observer
	RetryOption    = canonasync.RetryOption
	RetryableError = canonasync.RetryableError
)

// Functions

func DrainAll() DrainStrategy {
	return canonasync.DrainAll()
}

func DrainNone() DrainStrategy {
	return canonasync.DrainNone()
}

func DrainReady(debounce time.Duration) DrainStrategy {
	return canonasync.DrainReady(debounce)
}

func Retry(fn functions.BlockingAsyncOp, opts ...RetryOption) functions.BlockingAsyncOp {
	return canonasync.Retry(fn, opts...)
}

func RetryAttempts(attempts int) RetryOption {
	return canonasync.RetryAttempts(attempts)
}

func RetryBackoff(backoff time.Duration) RetryOption {
	return canonasync.RetryBackoff(backoff)
}

func RetryBinding(fn functions.BlockingAsyncOp, opts ...RetryOption) decls.OverloadOpt {
	return canonasync.RetryBinding(fn, opts...)
}

func Timeout(fn functions.BlockingAsyncOp, timeout time.Duration) functions.BlockingAsyncOp {
	return canonasync.Timeout(fn, timeout)
}

func TimeoutBinding(fn functions.BlockingAsyncOp, timeout time.Duration) decls.OverloadOpt {
	return canonasync.TimeoutBinding(fn, timeout)
}
