// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package traits

import (
	canontraits "cel.dev/cel-go/common/types/traits"
)

// Type aliases
type (
	Adder         = canontraits.Adder
	Comparer      = canontraits.Comparer
	Container     = canontraits.Container
	Divider       = canontraits.Divider
	FieldTester   = canontraits.FieldTester
	Foldable      = canontraits.Foldable
	Folder        = canontraits.Folder
	Indexer       = canontraits.Indexer
	Iterable      = canontraits.Iterable
	Iterator      = canontraits.Iterator
	Lister        = canontraits.Lister
	Mapper        = canontraits.Mapper
	Matcher       = canontraits.Matcher
	Modder        = canontraits.Modder
	Multiplier    = canontraits.Multiplier
	MutableLister = canontraits.MutableLister
	MutableMapper = canontraits.MutableMapper
	Negater       = canontraits.Negater
	Receiver      = canontraits.Receiver
	Sizer         = canontraits.Sizer
	Subtractor    = canontraits.Subtractor
	Zeroer        = canontraits.Zeroer
)

// Constants
const (
	AdderType       = canontraits.AdderType
	ComparerType    = canontraits.ComparerType
	ContainerType   = canontraits.ContainerType
	DividerType     = canontraits.DividerType
	FieldTesterType = canontraits.FieldTesterType
	FoldableType    = canontraits.FoldableType
	IndexerType     = canontraits.IndexerType
	IterableType    = canontraits.IterableType
	IteratorType    = canontraits.IteratorType
	ListerType      = canontraits.ListerType
	MapperType      = canontraits.MapperType
	MatcherType     = canontraits.MatcherType
	ModderType      = canontraits.ModderType
	MultiplierType  = canontraits.MultiplierType
	NegatorType     = canontraits.NegatorType
	ReceiverType    = canontraits.ReceiverType
	SizerType       = canontraits.SizerType
	SubtractorType  = canontraits.SubtractorType
)
