// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package decls

import (
	canondecls "cel.dev/cel-go/checker/decls"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

// Variables
var (
	Any       = canondecls.Any
	Bool      = canondecls.Bool
	Bytes     = canondecls.Bytes
	Double    = canondecls.Double
	Duration  = canondecls.Duration
	Dyn       = canondecls.Dyn
	Error     = canondecls.Error
	Int       = canondecls.Int
	Null      = canondecls.Null
	String    = canondecls.String
	Timestamp = canondecls.Timestamp
	Uint      = canondecls.Uint
)

// Functions

func NewAbstractType(name string, paramTypes ...*exprpb.Type) *exprpb.Type {
	return canondecls.NewAbstractType(name, paramTypes...)
}

func NewConst(name string, t *exprpb.Type, v *exprpb.Constant) *exprpb.Decl {
	return canondecls.NewConst(name, t, v)
}

func NewFunction(name string,
	overloads ...*exprpb.Decl_FunctionDecl_Overload) *exprpb.Decl {
	return canondecls.NewFunction(name, overloads...)
}

func NewFunctionType(resultType *exprpb.Type,
	argTypes ...*exprpb.Type) *exprpb.Type {
	return canondecls.NewFunctionType(resultType, argTypes...)
}

func NewFunctionWithDoc(name, doc string,
	overloads ...*exprpb.Decl_FunctionDecl_Overload) *exprpb.Decl {
	return canondecls.NewFunctionWithDoc(name, doc, overloads...)
}

func NewIdent(name string, t *exprpb.Type, v *exprpb.Constant) *exprpb.Decl {
	return canondecls.NewIdent(name, t, v)
}

func NewInstanceOverload(id string, argTypes []*exprpb.Type, resultType *exprpb.Type) *exprpb.Decl_FunctionDecl_Overload {
	return canondecls.NewInstanceOverload(id, argTypes, resultType)
}

func NewListType(elem *exprpb.Type) *exprpb.Type {
	return canondecls.NewListType(elem)
}

func NewMapType(key *exprpb.Type, value *exprpb.Type) *exprpb.Type {
	return canondecls.NewMapType(key, value)
}

func NewObjectType(typeName string) *exprpb.Type {
	return canondecls.NewObjectType(typeName)
}

func NewOptionalType(paramType *exprpb.Type) *exprpb.Type {
	return canondecls.NewOptionalType(paramType)
}

func NewOverload(id string, argTypes []*exprpb.Type, resultType *exprpb.Type) *exprpb.Decl_FunctionDecl_Overload {
	return canondecls.NewOverload(id, argTypes, resultType)
}

func NewParameterizedInstanceOverload(id string,
	argTypes []*exprpb.Type,
	resultType *exprpb.Type,
	typeParams []string) *exprpb.Decl_FunctionDecl_Overload {
	return canondecls.NewParameterizedInstanceOverload(id, argTypes, resultType, typeParams)
}

func NewParameterizedOverload(id string,
	argTypes []*exprpb.Type,
	resultType *exprpb.Type,
	typeParams []string) *exprpb.Decl_FunctionDecl_Overload {
	return canondecls.NewParameterizedOverload(id, argTypes, resultType, typeParams)
}

func NewPrimitiveType(primitive exprpb.Type_PrimitiveType) *exprpb.Type {
	return canondecls.NewPrimitiveType(primitive)
}

func NewTypeParamType(name string) *exprpb.Type {
	return canondecls.NewTypeParamType(name)
}

func NewTypeType(nested *exprpb.Type) *exprpb.Type {
	return canondecls.NewTypeType(nested)
}

func NewVar(name string, t *exprpb.Type) *exprpb.Decl {
	return canondecls.NewVar(name, t)
}

func NewVarWithDoc(name string, t *exprpb.Type, desc string) *exprpb.Decl {
	return canondecls.NewVarWithDoc(name, t, desc)
}

func NewWellKnownType(wellKnown exprpb.Type_WellKnownType) *exprpb.Type {
	return canondecls.NewWellKnownType(wellKnown)
}

func NewWrapperType(wrapped *exprpb.Type) *exprpb.Type {
	return canondecls.NewWrapperType(wrapped)
}
