// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package ast

import (
	"cel.dev/cel-go/common"
	canonast "cel.dev/cel-go/common/ast"
	"cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/ref"
	celpb "cel.dev/expr"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

// Type aliases
type (
	AST                = canonast.AST
	CallExpr           = canonast.CallExpr
	ComprehensionExpr  = canonast.ComprehensionExpr
	EntryExpr          = canonast.EntryExpr
	EntryExprKind      = canonast.EntryExprKind
	Expr               = canonast.Expr
	ExprFactory        = canonast.ExprFactory
	ExprKind           = canonast.ExprKind
	ExprMatcher        = canonast.ExprMatcher
	Extension          = canonast.Extension
	ExtensionComponent = canonast.ExtensionComponent
	ExtensionVersion   = canonast.ExtensionVersion
	IDGenerator        = canonast.IDGenerator
	ListExpr           = canonast.ListExpr
	MapEntry           = canonast.MapEntry
	MapExpr            = canonast.MapExpr
	NavigableExpr      = canonast.NavigableExpr
	OffsetRange        = canonast.OffsetRange
	ReferenceInfo      = canonast.ReferenceInfo
	SelectExpr         = canonast.SelectExpr
	SourceInfo         = canonast.SourceInfo
	StructExpr         = canonast.StructExpr
	StructField        = canonast.StructField
	Visitor            = canonast.Visitor
)

// Constants
const (
	CallKind                 = canonast.CallKind
	ComponentParser          = canonast.ComponentParser
	ComponentRuntime         = canonast.ComponentRuntime
	ComponentTypeChecker     = canonast.ComponentTypeChecker
	ComprehensionKind        = canonast.ComprehensionKind
	IdentKind                = canonast.IdentKind
	ListKind                 = canonast.ListKind
	LiteralKind              = canonast.LiteralKind
	MapEntryKind             = canonast.MapEntryKind
	MapKind                  = canonast.MapKind
	SelectKind               = canonast.SelectKind
	StructFieldKind          = canonast.StructFieldKind
	StructKind               = canonast.StructKind
	UnspecifiedEntryExprKind = canonast.UnspecifiedEntryExprKind
	UnspecifiedExprKind      = canonast.UnspecifiedExprKind
)

// Functions

func AllMatcher() ExprMatcher {
	return canonast.AllMatcher()
}

func AlphaProtoConstantAsVal(c *exprpb.Constant) (ref.Val, error) {
	return canonast.AlphaProtoConstantAsVal(c)
}

func ConstantToVal(c *exprpb.Constant) (ref.Val, error) {
	return canonast.ConstantToVal(c)
}

func ConstantValueMatcher() ExprMatcher {
	return canonast.ConstantValueMatcher()
}

func Copy(a *AST) *AST {
	return canonast.Copy(a)
}

func CopySourceInfo(info *SourceInfo) *SourceInfo {
	return canonast.CopySourceInfo(info)
}

func EntryExprToProto(e EntryExpr) (*exprpb.Expr_CreateStruct_Entry, error) {
	return canonast.EntryExprToProto(e)
}

func ExceedsDepth(a *AST, maxDepth int) bool {
	return canonast.ExceedsDepth(a, maxDepth)
}

func ExprToProto(e Expr) (*exprpb.Expr, error) {
	return canonast.ExprToProto(e)
}

func FunctionMatcher(funcName string) ExprMatcher {
	return canonast.FunctionMatcher(funcName)
}

func Heights(a *AST) map[int64]int {
	return canonast.Heights(a)
}

func KindMatcher(kind ExprKind) ExprMatcher {
	return canonast.KindMatcher(kind)
}

func MatchDescendants(expr NavigableExpr, matcher ExprMatcher) []NavigableExpr {
	return canonast.MatchDescendants(expr, matcher)
}

func MatchSubset(exprs []NavigableExpr, matcher ExprMatcher) []NavigableExpr {
	return canonast.MatchSubset(exprs, matcher)
}

func MaxID(a *AST) int64 {
	return canonast.MaxID(a)
}

func NavigateAST(ast *AST) NavigableExpr {
	return canonast.NavigateAST(ast)
}

func NavigateExpr(ast *AST, expr Expr) NavigableExpr {
	return canonast.NavigateExpr(ast, expr)
}

func NewAST(e Expr, sourceInfo *SourceInfo) *AST {
	return canonast.NewAST(e, sourceInfo)
}

func NewCheckedAST(parsed *AST, typeMap map[int64]*types.Type, refMap map[int64]*ReferenceInfo) *AST {
	return canonast.NewCheckedAST(parsed, typeMap, refMap)
}

func NewExprFactory() ExprFactory {
	return canonast.NewExprFactory()
}

func NewExprFactoryWithAccumulator(id string) ExprFactory {
	return canonast.NewExprFactoryWithAccumulator(id)
}

func NewExprVisitor(v func(Expr)) Visitor {
	return canonast.NewExprVisitor(v)
}

func NewExtension(id string, version ExtensionVersion, components ...ExtensionComponent) Extension {
	return canonast.NewExtension(id, version, components...)
}

func NewExtensionVersion(major, minor int64) ExtensionVersion {
	return canonast.NewExtensionVersion(major, minor)
}

func NewFunctionReference(overloads ...string) *ReferenceInfo {
	return canonast.NewFunctionReference(overloads...)
}

func NewIdentReference(name string, value ref.Val) *ReferenceInfo {
	return canonast.NewIdentReference(name, value)
}

func NewSourceInfo(src common.Source) *SourceInfo {
	return canonast.NewSourceInfo(src)
}

func NodeCount(a *AST) int {
	return canonast.NodeCount(a)
}

func PostOrderVisit(expr Expr, visitor Visitor) {
	canonast.PostOrderVisit(expr, visitor)
}

func PreOrderVisit(expr Expr, visitor Visitor) {
	canonast.PreOrderVisit(expr, visitor)
}

func ProtoConstantAsVal(c *celpb.Constant) (ref.Val, error) {
	return canonast.ProtoConstantAsVal(c)
}

func ProtoToEntryExpr(e *exprpb.Expr_CreateStruct_Entry) (EntryExpr, error) {
	return canonast.ProtoToEntryExpr(e)
}

func ProtoToExpr(e *exprpb.Expr) (Expr, error) {
	return canonast.ProtoToExpr(e)
}

func ProtoToReferenceInfo(ref *exprpb.Reference) (*ReferenceInfo, error) {
	return canonast.ProtoToReferenceInfo(ref)
}

func ProtoToSourceInfo(info *exprpb.SourceInfo) (*SourceInfo, error) {
	return canonast.ProtoToSourceInfo(info)
}

func ReferenceInfoToProto(info *ReferenceInfo) (*exprpb.Reference, error) {
	return canonast.ReferenceInfoToProto(info)
}

func SourceInfoToProto(info *SourceInfo) (*exprpb.SourceInfo, error) {
	return canonast.SourceInfoToProto(info)
}

func ToAST(checked *exprpb.CheckedExpr) (*AST, error) {
	return canonast.ToAST(checked)
}

func ToProto(ast *AST) (*exprpb.CheckedExpr, error) {
	return canonast.ToProto(ast)
}

func ValToConstant(v ref.Val) (*exprpb.Constant, error) {
	return canonast.ValToConstant(v)
}
