// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package pb

import (
	canonpb "cel.dev/cel-go/common/types/pb"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Type aliases
type (
	Db                   = canonpb.Db
	DbOption             = canonpb.DbOption
	EnumValueDescription = canonpb.EnumValueDescription
	FieldDescription     = canonpb.FieldDescription
	FileDescription      = canonpb.FileDescription
	Map                  = canonpb.Map
	TypeDescription      = canonpb.TypeDescription
)

// Variables
var (
	CheckedPrimitives = canonpb.CheckedPrimitives
	CheckedWellKnowns = canonpb.CheckedWellKnowns
	DefaultDb         = canonpb.DefaultDb
)

// Functions

func CollectFileDescriptorSet(message proto.Message) map[string]protoreflect.FileDescriptor {
	return canonpb.CollectFileDescriptorSet(message)
}

func Equal(x, y proto.Message) bool {
	return canonpb.Equal(x, y)
}

func JSONFieldNames(enabled bool) DbOption {
	return canonpb.JSONFieldNames(enabled)
}

func Merge(dstPB, srcPB proto.Message) error {
	return canonpb.Merge(dstPB, srcPB)
}

func NewDb(opts ...DbOption) *Db {
	return canonpb.NewDb(opts...)
}
