// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package proto2pb

import (
	canonproto2pb "cel.dev/cel-go/test/proto2pb"
)

// Type aliases
type (
	ExampleType                      = canonproto2pb.ExampleType
	ExtendedExampleType              = canonproto2pb.ExtendedExampleType
	ExternalMessageType              = canonproto2pb.ExternalMessageType
	GlobalEnum                       = canonproto2pb.GlobalEnum
	NestedTestAllTypes               = canonproto2pb.NestedTestAllTypes
	TestAllTypes                     = canonproto2pb.TestAllTypes
	TestAllTypes_NestedEnum          = canonproto2pb.TestAllTypes_NestedEnum
	TestAllTypes_NestedGroup         = canonproto2pb.TestAllTypes_NestedGroup
	TestAllTypes_NestedMessage       = canonproto2pb.TestAllTypes_NestedMessage
	TestAllTypes_SingleNestedEnum    = canonproto2pb.TestAllTypes_SingleNestedEnum
	TestAllTypes_SingleNestedMessage = canonproto2pb.TestAllTypes_SingleNestedMessage
)

// Constants
const (
	Default_TestAllTypes_SingleBool       = canonproto2pb.Default_TestAllTypes_SingleBool
	Default_TestAllTypes_SingleDouble     = canonproto2pb.Default_TestAllTypes_SingleDouble
	Default_TestAllTypes_SingleFloat      = canonproto2pb.Default_TestAllTypes_SingleFloat
	Default_TestAllTypes_SingleInt32      = canonproto2pb.Default_TestAllTypes_SingleInt32
	Default_TestAllTypes_SingleInt64      = canonproto2pb.Default_TestAllTypes_SingleInt64
	Default_TestAllTypes_SingleNestedEnum = canonproto2pb.Default_TestAllTypes_SingleNestedEnum
	Default_TestAllTypes_SingleString     = canonproto2pb.Default_TestAllTypes_SingleString
	Default_TestAllTypes_SingleUint32     = canonproto2pb.Default_TestAllTypes_SingleUint32
	Default_TestAllTypes_SingleUint64     = canonproto2pb.Default_TestAllTypes_SingleUint64
	GlobalEnum_GAR                        = canonproto2pb.GlobalEnum_GAR
	GlobalEnum_GAZ                        = canonproto2pb.GlobalEnum_GAZ
	GlobalEnum_GOO                        = canonproto2pb.GlobalEnum_GOO
	TestAllTypes_BAR                      = canonproto2pb.TestAllTypes_BAR
	TestAllTypes_BAZ                      = canonproto2pb.TestAllTypes_BAZ
	TestAllTypes_FOO                      = canonproto2pb.TestAllTypes_FOO
)

// Variables
var (
	Default_TestAllTypes_SingleBytes         = canonproto2pb.Default_TestAllTypes_SingleBytes
	E_ExtendedExampleType_EnumExt            = canonproto2pb.E_ExtendedExampleType_EnumExt
	E_ExtendedExampleType_ExtendedExamples   = canonproto2pb.E_ExtendedExampleType_ExtendedExamples
	E_ExternalMessageType_Int64Ext           = canonproto2pb.E_ExternalMessageType_Int64Ext
	E_Int32Ext                               = canonproto2pb.E_Int32Ext
	E_Int32WrapperExt                        = canonproto2pb.E_Int32WrapperExt
	E_NestedExample                          = canonproto2pb.E_NestedExample
	File_test_proto2pb_test_all_types_proto  = canonproto2pb.File_test_proto2pb_test_all_types_proto
	File_test_proto2pb_test_extensions_proto = canonproto2pb.File_test_proto2pb_test_extensions_proto
	GlobalEnum_name                          = canonproto2pb.GlobalEnum_name
	GlobalEnum_value                         = canonproto2pb.GlobalEnum_value
	TestAllTypes_NestedEnum_name             = canonproto2pb.TestAllTypes_NestedEnum_name
	TestAllTypes_NestedEnum_value            = canonproto2pb.TestAllTypes_NestedEnum_value
)
