// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto2";

package google.expr.proto2.test;

option go_package = "cel.dev/cel-go/test/proto2pb";

import "google/protobuf/wrappers.proto";
import "test/proto2pb/test_all_types.proto";

// Package scoped extensions.
extend ExampleType {
  optional ExampleType nested_example = 100;
  optional int32 int32_ext = 101;
  optional google.protobuf.Int32Value int32_wrapper_ext = 102;
}

// Message scoped extensions.
message ExternalMessageType {
  extend ExampleType {
    optional int64 int64_ext = 201;
  }
}