// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package env

import (
	canonenv "cel.dev/cel-go/common/env"
	"cel.dev/cel-go/common/types"
)

// Type aliases
type (
	Config          = canonenv.Config
	ContextVariable = canonenv.ContextVariable
	Extension       = canonenv.Extension
	Feature         = canonenv.Feature
	Function        = canonenv.Function
	Import          = canonenv.Import
	LibrarySubset   = canonenv.LibrarySubset
	Limit           = canonenv.Limit
	Overload        = canonenv.Overload
	TypeDesc        = canonenv.TypeDesc
	Validator       = canonenv.Validator
	Variable        = canonenv.Variable
)

// Functions

func ConfigFromYAML(data []byte) (*Config, error) {
	return canonenv.ConfigFromYAML(data)
}

func ConfigToYAML(c *Config) ([]byte, error) {
	return canonenv.ConfigToYAML(c)
}

func NewConfig(name string) *Config {
	return canonenv.NewConfig(name)
}

func NewContextVariable(typeName string) *ContextVariable {
	return canonenv.NewContextVariable(typeName)
}

func NewExtension(name string, version uint32) *Extension {
	return canonenv.NewExtension(name, version)
}

func NewFeature(name string, enabled bool) *Feature {
	return canonenv.NewFeature(name, enabled)
}

func NewFunction(name string, overloads ...*Overload) *Function {
	return canonenv.NewFunction(name, overloads...)
}

func NewFunctionWithDoc(name, doc string, overloads ...*Overload) *Function {
	return canonenv.NewFunctionWithDoc(name, doc, overloads...)
}

func NewImport(name string) *Import {
	return canonenv.NewImport(name)
}

func NewLibrarySubset() *LibrarySubset {
	return canonenv.NewLibrarySubset()
}

func NewLimit(name string, value int) *Limit {
	return canonenv.NewLimit(name, value)
}

func NewMemberOverload(id string, target *TypeDesc, args []*TypeDesc, ret *TypeDesc, examples ...string) *Overload {
	return canonenv.NewMemberOverload(id, target, args, ret, examples...)
}

func NewOverload(id string, args []*TypeDesc, ret *TypeDesc, examples ...string) *Overload {
	return canonenv.NewOverload(id, args, ret, examples...)
}

func NewTypeDesc(typeName string, params ...*TypeDesc) *TypeDesc {
	return canonenv.NewTypeDesc(typeName, params...)
}

func NewTypeParam(paramName string) *TypeDesc {
	return canonenv.NewTypeParam(paramName)
}

func NewValidator(name string) *Validator {
	return canonenv.NewValidator(name)
}

func NewVariable(name string, t *TypeDesc) *Variable {
	return canonenv.NewVariable(name, t)
}

func NewVariableWithDoc(name string, t *TypeDesc, doc string) *Variable {
	return canonenv.NewVariableWithDoc(name, t, doc)
}

func ParseTypeDesc(text string) (*TypeDesc, error) {
	return canonenv.ParseTypeDesc(text)
}

func SerializeTypeDesc(t *types.Type) *TypeDesc {
	return canonenv.SerializeTypeDesc(t)
}
