// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package parser

import (
	"cel.dev/cel-go/common"
	"cel.dev/cel-go/common/ast"
	canonparser "cel.dev/cel-go/parser"
)

// Type aliases
type (
	ExprHelper     = canonparser.ExprHelper
	Macro          = canonparser.Macro
	MacroExpander  = canonparser.MacroExpander
	MacroOpt       = canonparser.MacroOpt
	Option         = canonparser.Option
	Parser         = canonparser.Parser
	UnparserOption = canonparser.UnparserOption
)

// Constants
const (
	AccumulatorName       = canonparser.AccumulatorName
	HiddenAccumulatorName = canonparser.HiddenAccumulatorName
)

// Variables
var (
	AllMacro          = canonparser.AllMacro
	AllMacros         = canonparser.AllMacros
	ExistsMacro       = canonparser.ExistsMacro
	ExistsOneMacro    = canonparser.ExistsOneMacro
	ExistsOneMacroNew = canonparser.ExistsOneMacroNew
	FilterMacro       = canonparser.FilterMacro
	HasMacro          = canonparser.HasMacro
	MapFilterMacro    = canonparser.MapFilterMacro
	MapMacro          = canonparser.MapMacro
	NoMacros          = canonparser.NoMacros
)

// Functions

func EnableHiddenAccumulatorName(enabled bool) Option {
	return canonparser.EnableHiddenAccumulatorName(enabled)
}

func EnableIdentEscapeSyntax(enableIdentEscapeSyntax bool) Option {
	return canonparser.EnableIdentEscapeSyntax(enableIdentEscapeSyntax)
}

func EnableOptionalSyntax(optionalSyntax bool) Option {
	return canonparser.EnableOptionalSyntax(optionalSyntax)
}

func EnableVariadicOperatorASTs(varArgASTs bool) Option {
	return canonparser.EnableVariadicOperatorASTs(varArgASTs)
}

func ErrorRecoveryLimit(limit int) Option {
	return canonparser.ErrorRecoveryLimit(limit)
}

func ErrorRecoveryLookaheadTokenLimit(limit int) Option {
	return canonparser.ErrorRecoveryLookaheadTokenLimit(limit)
}

func ErrorReportingLimit(limit int) Option {
	return canonparser.ErrorReportingLimit(limit)
}

func ExpressionSizeCodePointLimit(expressionSizeCodePointLimit int) Option {
	return canonparser.ExpressionSizeCodePointLimit(expressionSizeCodePointLimit)
}

func MacroDocs(docs ...string) MacroOpt {
	return canonparser.MacroDocs(docs...)
}

func MacroExamples(examples ...string) MacroOpt {
	return canonparser.MacroExamples(examples...)
}

func Macros(macros ...Macro) Option {
	return canonparser.Macros(macros...)
}

func MakeAll(eh ExprHelper, target ast.Expr, args []ast.Expr) (ast.Expr, *common.Error) {
	return canonparser.MakeAll(eh, target, args)
}

func MakeExists(eh ExprHelper, target ast.Expr, args []ast.Expr) (ast.Expr, *common.Error) {
	return canonparser.MakeExists(eh, target, args)
}

func MakeExistsOne(eh ExprHelper, target ast.Expr, args []ast.Expr) (ast.Expr, *common.Error) {
	return canonparser.MakeExistsOne(eh, target, args)
}

func MakeFilter(eh ExprHelper, target ast.Expr, args []ast.Expr) (ast.Expr, *common.Error) {
	return canonparser.MakeFilter(eh, target, args)
}

func MakeHas(eh ExprHelper, target ast.Expr, args []ast.Expr) (ast.Expr, *common.Error) {
	return canonparser.MakeHas(eh, target, args)
}

func MakeMap(eh ExprHelper, target ast.Expr, args []ast.Expr) (ast.Expr, *common.Error) {
	return canonparser.MakeMap(eh, target, args)
}

func MaxExpressionNodeCount(limit int) Option {
	return canonparser.MaxExpressionNodeCount(limit)
}

func MaxRecursionDepth(limit int) Option {
	return canonparser.MaxRecursionDepth(limit)
}

func NewGlobalMacro(function string, argCount int, expander MacroExpander, opts ...MacroOpt) Macro {
	return canonparser.NewGlobalMacro(function, argCount, expander, opts...)
}

func NewGlobalVarArgMacro(function string, expander MacroExpander, opts ...MacroOpt) Macro {
	return canonparser.NewGlobalVarArgMacro(function, expander, opts...)
}

func NewParser(opts ...Option) (*Parser, error) {
	return canonparser.NewParser(opts...)
}

func NewReceiverMacro(function string, argCount int, expander MacroExpander, opts ...MacroOpt) Macro {
	return canonparser.NewReceiverMacro(function, argCount, expander, opts...)
}

func NewReceiverVarArgMacro(function string, expander MacroExpander, opts ...MacroOpt) Macro {
	return canonparser.NewReceiverVarArgMacro(function, expander, opts...)
}

func Parse(source common.Source) (*ast.AST, *common.Errors) {
	return canonparser.Parse(source)
}

func PopulateMacroCalls(populateMacroCalls bool) Option {
	return canonparser.PopulateMacroCalls(populateMacroCalls)
}

func Unparse(expr ast.Expr, info *ast.SourceInfo, opts ...UnparserOption) (string, error) {
	return canonparser.Unparse(expr, info, opts...)
}

func WrapAfterColumnLimit(wrapAfter bool) UnparserOption {
	return canonparser.WrapAfterColumnLimit(wrapAfter)
}

func WrapOnColumn(col int) UnparserOption {
	return canonparser.WrapOnColumn(col)
}

func WrapOnOperators(symbols ...string) UnparserOption {
	return canonparser.WrapOnOperators(symbols...)
}
