load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(
    licenses = ["notice"],  # Apache 2.0
)

go_library(
    name = "go_default_library",
    srcs = ["alias.go"],
    importpath = "github.com/google/cel-go/parser",
    visibility = ["//visibility:public"],
    deps = [
        "@dev_cel_cel_go//common:go_default_library",
        "@dev_cel_cel_go//common/ast:go_default_library",
        "@dev_cel_cel_go//parser:go_default_library",
    ],
)
