// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package ext

import (
	"cel.dev/cel-go/cel"
	"cel.dev/cel-go/common/types/ref"
	canonext "cel.dev/cel-go/ext"
)

// Type aliases
type (
	BindingsOption              = canonext.BindingsOption
	CIDR                        = canonext.CIDR
	EncodersOption              = canonext.EncodersOption
	IP                          = canonext.IP
	ListsOption                 = canonext.ListsOption
	MathOption                  = canonext.MathOption
	NativeTypesFieldNameHandler = canonext.NativeTypesFieldNameHandler
	NativeTypesOption           = canonext.NativeTypesOption
	NetworkOption               = canonext.NetworkOption
	ProtosOption                = canonext.ProtosOption
	RegexOptions                = canonext.RegexOptions
	SetsOption                  = canonext.SetsOption
	StringsOption               = canonext.StringsOption
	TwoVarComprehensionsOption  = canonext.TwoVarComprehensionsOption
)

// Constants
const (
	Version1 = canonext.Version1
)

// Variables
var (
	CIDRType         = canonext.CIDRType
	IPType           = canonext.IPType
	ParseStructField = canonext.ParseStructField
	ParseStructTag   = canonext.ParseStructTag
	ParseStructTags  = canonext.ParseStructTags
)

// Functions

func Bindings(options ...BindingsOption) cel.EnvOption {
	return canonext.Bindings(options...)
}

func BindingsVersion(version uint32) BindingsOption {
	return canonext.BindingsVersion(version)
}

func Encoders(options ...EncodersOption) cel.EnvOption {
	return canonext.Encoders(options...)
}

func EncodersVersion(version uint32) EncodersOption {
	return canonext.EncodersVersion(version)
}

func ExtensionOptionFactory(configElement any) (cel.EnvOption, bool) {
	return canonext.ExtensionOptionFactory(configElement)
}

func FormatString(arg ref.Val, locale string) (string, error) {
	return canonext.FormatString(arg, locale)
}

func Lists(options ...ListsOption) cel.EnvOption {
	return canonext.Lists(options...)
}

func ListsMaxRangeSize(size int64) ListsOption {
	return canonext.ListsMaxRangeSize(size)
}

func ListsVersion(version uint32) ListsOption {
	return canonext.ListsVersion(version)
}

func Math(options ...MathOption) cel.EnvOption {
	return canonext.Math(options...)
}

func MathVersion(version uint32) MathOption {
	return canonext.MathVersion(version)
}

func NativeTypes(args ...any) cel.EnvOption {
	return canonext.NativeTypes(args...)
}

func NativeTypesVersion(version uint32) NativeTypesOption {
	return canonext.NativeTypesVersion(version)
}

func Network(opts ...NetworkOption) cel.EnvOption {
	return canonext.Network(opts...)
}

func NetworkVersion(version uint32) NetworkOption {
	return canonext.NetworkVersion(version)
}

func NewSetMembershipOptimizer() (cel.ASTOptimizer, error) {
	return canonext.NewSetMembershipOptimizer()
}

func Protos(options ...ProtosOption) cel.EnvOption {
	return canonext.Protos(options...)
}

func ProtosVersion(version uint32) ProtosOption {
	return canonext.ProtosVersion(version)
}

func Regex(options ...RegexOptions) cel.EnvOption {
	return canonext.Regex(options...)
}

func RegexVersion(version uint32) RegexOptions {
	return canonext.RegexVersion(version)
}

func Sets(options ...SetsOption) cel.EnvOption {
	return canonext.Sets(options...)
}

func SetsVersion(version uint32) SetsOption {
	return canonext.SetsVersion(version)
}

func Strings(options ...StringsOption) cel.EnvOption {
	return canonext.Strings(options...)
}

func StringsLocale(locale string) StringsOption {
	return canonext.StringsLocale(locale)
}

func StringsMaxPrecision(limit int) StringsOption {
	return canonext.StringsMaxPrecision(limit)
}

func StringsValidateFormatCalls(value bool) StringsOption {
	return canonext.StringsValidateFormatCalls(value)
}

func StringsVersion(version uint32) StringsOption {
	return canonext.StringsVersion(version)
}

func TwoVarComprehensions(options ...TwoVarComprehensionsOption) cel.EnvOption {
	return canonext.TwoVarComprehensions(options...)
}

func TwoVarComprehensionsVersion(version uint32) TwoVarComprehensionsOption {
	return canonext.TwoVarComprehensionsVersion(version)
}
