// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package operators

import (
	canonoperators "cel.dev/cel-go/common/operators"
)

// Constants
const (
	Add                 = canonoperators.Add
	All                 = canonoperators.All
	Conditional         = canonoperators.Conditional
	Divide              = canonoperators.Divide
	Equals              = canonoperators.Equals
	Exists              = canonoperators.Exists
	ExistsOne           = canonoperators.ExistsOne
	Filter              = canonoperators.Filter
	Greater             = canonoperators.Greater
	GreaterEquals       = canonoperators.GreaterEquals
	Has                 = canonoperators.Has
	In                  = canonoperators.In
	Index               = canonoperators.Index
	Less                = canonoperators.Less
	LessEquals          = canonoperators.LessEquals
	LogicalAnd          = canonoperators.LogicalAnd
	LogicalNot          = canonoperators.LogicalNot
	LogicalOr           = canonoperators.LogicalOr
	Map                 = canonoperators.Map
	Modulo              = canonoperators.Modulo
	Multiply            = canonoperators.Multiply
	Negate              = canonoperators.Negate
	NotEquals           = canonoperators.NotEquals
	NotStrictlyFalse    = canonoperators.NotStrictlyFalse
	OldIn               = canonoperators.OldIn
	OldNotStrictlyFalse = canonoperators.OldNotStrictlyFalse
	OptIndex            = canonoperators.OptIndex
	OptSelect           = canonoperators.OptSelect
	Subtract            = canonoperators.Subtract
)

// Functions

func Arity(symbol string) int {
	return canonoperators.Arity(symbol)
}

func Find(text string) (string, bool) {
	return canonoperators.Find(text)
}

func FindReverse(symbol string) (string, bool) {
	return canonoperators.FindReverse(symbol)
}

func FindReverseBinaryOperator(symbol string) (string, bool) {
	return canonoperators.FindReverseBinaryOperator(symbol)
}

func Precedence(symbol string) int {
	return canonoperators.Precedence(symbol)
}
