// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package proto3pb

import (
	canonproto3pb "cel.dev/cel-go/test/proto3pb"
)

// Type aliases
type (
	GlobalEnum                       = canonproto3pb.GlobalEnum
	ImportedGlobalEnum               = canonproto3pb.ImportedGlobalEnum
	NestedTestAllTypes               = canonproto3pb.NestedTestAllTypes
	TestAllTypes                     = canonproto3pb.TestAllTypes
	TestAllTypes_NestedEnum          = canonproto3pb.TestAllTypes_NestedEnum
	TestAllTypes_NestedMessage       = canonproto3pb.TestAllTypes_NestedMessage
	TestAllTypes_SingleNestedEnum    = canonproto3pb.TestAllTypes_SingleNestedEnum
	TestAllTypes_SingleNestedMessage = canonproto3pb.TestAllTypes_SingleNestedMessage
	TestJsonNames                    = canonproto3pb.TestJsonNames
)

// Constants
const (
	GlobalEnum_GAR                = canonproto3pb.GlobalEnum_GAR
	GlobalEnum_GAZ                = canonproto3pb.GlobalEnum_GAZ
	GlobalEnum_GOO                = canonproto3pb.GlobalEnum_GOO
	ImportedGlobalEnum_IMPORT_BAR = canonproto3pb.ImportedGlobalEnum_IMPORT_BAR
	ImportedGlobalEnum_IMPORT_BAZ = canonproto3pb.ImportedGlobalEnum_IMPORT_BAZ
	ImportedGlobalEnum_IMPORT_FOO = canonproto3pb.ImportedGlobalEnum_IMPORT_FOO
	TestAllTypes_BAR              = canonproto3pb.TestAllTypes_BAR
	TestAllTypes_BAZ              = canonproto3pb.TestAllTypes_BAZ
	TestAllTypes_FOO              = canonproto3pb.TestAllTypes_FOO
)

// Variables
var (
	File_test_proto3pb_test_all_types_proto = canonproto3pb.File_test_proto3pb_test_all_types_proto
	File_test_proto3pb_test_import_proto    = canonproto3pb.File_test_proto3pb_test_import_proto
	GlobalEnum_name                         = canonproto3pb.GlobalEnum_name
	GlobalEnum_value                        = canonproto3pb.GlobalEnum_value
	ImportedGlobalEnum_name                 = canonproto3pb.ImportedGlobalEnum_name
	ImportedGlobalEnum_value                = canonproto3pb.ImportedGlobalEnum_value
	TestAllTypes_NestedEnum_name            = canonproto3pb.TestAllTypes_NestedEnum_name
	TestAllTypes_NestedEnum_value           = canonproto3pb.TestAllTypes_NestedEnum_value
)
