// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/proto3pb/test_all_types.proto

package proto3pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalEnum int32

const (
	GlobalEnum_GOO GlobalEnum = 0
	GlobalEnum_GAR GlobalEnum = 1
	GlobalEnum_GAZ GlobalEnum = 2
)

var GlobalEnum_name = map[int32]string{
	0: "GOO",
	1: "GAR",
	2: "GAZ",
}

var GlobalEnum_value = map[string]int32{
	"GOO": 0,
	"GAR": 1,
	"GAZ": 2,
}

func (x GlobalEnum) String() string {
	return proto.EnumName(GlobalEnum_name, int32(x))
}

func (GlobalEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12a94cd3b88bedc6, []int{0}
}

type TestAllTypes_NestedEnum int32

const (
	TestAllTypes_FOO TestAllTypes_NestedEnum = 0
	TestAllTypes_BAR TestAllTypes_NestedEnum = 1
	TestAllTypes_BAZ TestAllTypes_NestedEnum = 2
)

var TestAllTypes_NestedEnum_name = map[int32]string{
	0: "FOO",
	1: "BAR",
	2: "BAZ",
}

var TestAllTypes_NestedEnum_value = map[string]int32{
	"FOO": 0,
	"BAR": 1,
	"BAZ": 2,
}

func (x TestAllTypes_NestedEnum) String() string {
	return proto.EnumName(TestAllTypes_NestedEnum_name, int32(x))
}

func (TestAllTypes_NestedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12a94cd3b88bedc6, []int{0, 0}
}

type TestAllTypes struct {
	SingleInt32         int32                 `protobuf:"varint,1,opt,name=single_int32,json=singleInt32,proto3" json:"single_int32,omitempty"`
	SingleInt64         int64                 `protobuf:"varint,2,opt,name=single_int64,json=singleInt64,proto3" json:"single_int64,omitempty"`
	SingleUint32        uint32                `protobuf:"varint,3,opt,name=single_uint32,json=singleUint32,proto3" json:"single_uint32,omitempty"`
	SingleUint64        uint64                `protobuf:"varint,4,opt,name=single_uint64,json=singleUint64,proto3" json:"single_uint64,omitempty"`
	SingleSint32        int32                 `protobuf:"zigzag32,5,opt,name=single_sint32,json=singleSint32,proto3" json:"single_sint32,omitempty"`
	SingleSint64        int64                 `protobuf:"zigzag64,6,opt,name=single_sint64,json=singleSint64,proto3" json:"single_sint64,omitempty"`
	SingleFixed32       uint32                `protobuf:"fixed32,7,opt,name=single_fixed32,json=singleFixed32,proto3" json:"single_fixed32,omitempty"`
	SingleFixed64       uint64                `protobuf:"fixed64,8,opt,name=single_fixed64,json=singleFixed64,proto3" json:"single_fixed64,omitempty"`
	SingleSfixed32      int32                 `protobuf:"fixed32,9,opt,name=single_sfixed32,json=singleSfixed32,proto3" json:"single_sfixed32,omitempty"`
	SingleSfixed64      int64                 `protobuf:"fixed64,10,opt,name=single_sfixed64,json=singleSfixed64,proto3" json:"single_sfixed64,omitempty"`
	SingleFloat         float32               `protobuf:"fixed32,11,opt,name=single_float,json=singleFloat,proto3" json:"single_float,omitempty"`
	SingleDouble        float64               `protobuf:"fixed64,12,opt,name=single_double,json=singleDouble,proto3" json:"single_double,omitempty"`
	SingleBool          bool                  `protobuf:"varint,13,opt,name=single_bool,json=singleBool,proto3" json:"single_bool,omitempty"`
	SingleString        string                `protobuf:"bytes,14,opt,name=single_string,json=singleString,proto3" json:"single_string,omitempty"`
	SingleBytes         []byte                `protobuf:"bytes,15,opt,name=single_bytes,json=singleBytes,proto3" json:"single_bytes,omitempty"`
	SingleAny           *any.Any              `protobuf:"bytes,100,opt,name=single_any,json=singleAny,proto3" json:"single_any,omitempty"`
	SingleDuration      *duration.Duration    `protobuf:"bytes,101,opt,name=single_duration,json=singleDuration,proto3" json:"single_duration,omitempty"`
	SingleTimestamp     *timestamp.Timestamp  `protobuf:"bytes,102,opt,name=single_timestamp,json=singleTimestamp,proto3" json:"single_timestamp,omitempty"`
	SingleStruct        *_struct.Struct       `protobuf:"bytes,103,opt,name=single_struct,json=singleStruct,proto3" json:"single_struct,omitempty"`
	SingleValue         *_struct.Value        `protobuf:"bytes,104,opt,name=single_value,json=singleValue,proto3" json:"single_value,omitempty"`
	SingleInt64Wrapper  *wrappers.Int64Value  `protobuf:"bytes,105,opt,name=single_int64_wrapper,json=singleInt64Wrapper,proto3" json:"single_int64_wrapper,omitempty"`
	SingleInt32Wrapper  *wrappers.Int32Value  `protobuf:"bytes,106,opt,name=single_int32_wrapper,json=singleInt32Wrapper,proto3" json:"single_int32_wrapper,omitempty"`
	SingleDoubleWrapper *wrappers.DoubleValue `protobuf:"bytes,107,opt,name=single_double_wrapper,json=singleDoubleWrapper,proto3" json:"single_double_wrapper,omitempty"`
	SingleFloatWrapper  *wrappers.FloatValue  `protobuf:"bytes,108,opt,name=single_float_wrapper,json=singleFloatWrapper,proto3" json:"single_float_wrapper,omitempty"`
	SingleUint64Wrapper *wrappers.UInt64Value `protobuf:"bytes,109,opt,name=single_uint64_wrapper,json=singleUint64Wrapper,proto3" json:"single_uint64_wrapper,omitempty"`
	SingleUint32Wrapper *wrappers.UInt32Value `protobuf:"bytes,110,opt,name=single_uint32_wrapper,json=singleUint32Wrapper,proto3" json:"single_uint32_wrapper,omitempty"`
	SingleStringWrapper *wrappers.StringValue `protobuf:"bytes,111,opt,name=single_string_wrapper,json=singleStringWrapper,proto3" json:"single_string_wrapper,omitempty"`
	SingleBoolWrapper   *wrappers.BoolValue   `protobuf:"bytes,112,opt,name=single_bool_wrapper,json=singleBoolWrapper,proto3" json:"single_bool_wrapper,omitempty"`
	SingleBytesWrapper  *wrappers.BytesValue  `protobuf:"bytes,113,opt,name=single_bytes_wrapper,json=singleBytesWrapper,proto3" json:"single_bytes_wrapper,omitempty"`
	// Types that are valid to be assigned to NestedType:
	//	*TestAllTypes_SingleNestedMessage
	//	*TestAllTypes_SingleNestedEnum
	NestedType            isTestAllTypes_NestedType     `protobuf_oneof:"nested_type"`
	RepeatedInt32         []int32                       `protobuf:"varint,31,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedInt64         []int64                       `protobuf:"varint,32,rep,packed,name=repeated_int64,json=repeatedInt64,proto3" json:"repeated_int64,omitempty"`
	RepeatedUint32        []uint32                      `protobuf:"varint,33,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3" json:"repeated_uint32,omitempty"`
	RepeatedUint64        []uint64                      `protobuf:"varint,34,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3" json:"repeated_uint64,omitempty"`
	RepeatedSint32        []int32                       `protobuf:"zigzag32,35,rep,packed,name=repeated_sint32,json=repeatedSint32,proto3" json:"repeated_sint32,omitempty"`
	RepeatedSint64        []int64                       `protobuf:"zigzag64,36,rep,packed,name=repeated_sint64,json=repeatedSint64,proto3" json:"repeated_sint64,omitempty"`
	RepeatedFixed32       []uint32                      `protobuf:"fixed32,37,rep,packed,name=repeated_fixed32,json=repeatedFixed32,proto3" json:"repeated_fixed32,omitempty"`
	RepeatedFixed64       []uint64                      `protobuf:"fixed64,38,rep,packed,name=repeated_fixed64,json=repeatedFixed64,proto3" json:"repeated_fixed64,omitempty"`
	RepeatedSfixed32      []int32                       `protobuf:"fixed32,39,rep,packed,name=repeated_sfixed32,json=repeatedSfixed32,proto3" json:"repeated_sfixed32,omitempty"`
	RepeatedSfixed64      []int64                       `protobuf:"fixed64,40,rep,packed,name=repeated_sfixed64,json=repeatedSfixed64,proto3" json:"repeated_sfixed64,omitempty"`
	RepeatedFloat         []float32                     `protobuf:"fixed32,41,rep,packed,name=repeated_float,json=repeatedFloat,proto3" json:"repeated_float,omitempty"`
	RepeatedDouble        []float64                     `protobuf:"fixed64,42,rep,packed,name=repeated_double,json=repeatedDouble,proto3" json:"repeated_double,omitempty"`
	RepeatedBool          []bool                        `protobuf:"varint,43,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedString        []string                      `protobuf:"bytes,44,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedBytes         [][]byte                      `protobuf:"bytes,45,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	RepeatedNestedMessage []*TestAllTypes_NestedMessage `protobuf:"bytes,48,rep,name=repeated_nested_message,json=repeatedNestedMessage,proto3" json:"repeated_nested_message,omitempty"`
	RepeatedNestedEnum    []TestAllTypes_NestedEnum     `protobuf:"varint,51,rep,packed,name=repeated_nested_enum,json=repeatedNestedEnum,proto3,enum=google.expr.proto3.test.TestAllTypes_NestedEnum" json:"repeated_nested_enum,omitempty"`
	RepeatedStringPiece   []string                      `protobuf:"bytes,54,rep,name=repeated_string_piece,json=repeatedStringPiece,proto3" json:"repeated_string_piece,omitempty"`
	RepeatedCord          []string                      `protobuf:"bytes,55,rep,name=repeated_cord,json=repeatedCord,proto3" json:"repeated_cord,omitempty"`
	RepeatedLazyMessage   []*TestAllTypes_NestedMessage `protobuf:"bytes,57,rep,name=repeated_lazy_message,json=repeatedLazyMessage,proto3" json:"repeated_lazy_message,omitempty"`
	MapStringString       map[string]string             `protobuf:"bytes,58,rep,name=map_string_string,json=mapStringString,proto3" json:"map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapInt64NestedType    map[int64]*NestedTestAllTypes `protobuf:"bytes,59,rep,name=map_int64_nested_type,json=mapInt64NestedType,proto3" json:"map_int64_nested_type,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ImportedEnums         []ImportedGlobalEnum          `protobuf:"varint,60,rep,packed,name=imported_enums,json=importedEnums,proto3,enum=google.expr.proto3.test.ImportedGlobalEnum" json:"imported_enums,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                      `json:"-"`
	XXX_unrecognized      []byte                        `json:"-"`
	XXX_sizecache         int32                         `json:"-"`
}

func (m *TestAllTypes) Reset()         { *m = TestAllTypes{} }
func (m *TestAllTypes) String() string { return proto.CompactTextString(m) }
func (*TestAllTypes) ProtoMessage()    {}
func (*TestAllTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a94cd3b88bedc6, []int{0}
}

func (m *TestAllTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAllTypes.Unmarshal(m, b)
}
func (m *TestAllTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAllTypes.Marshal(b, m, deterministic)
}
func (m *TestAllTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAllTypes.Merge(m, src)
}
func (m *TestAllTypes) XXX_Size() int {
	return xxx_messageInfo_TestAllTypes.Size(m)
}
func (m *TestAllTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAllTypes.DiscardUnknown(m)
}

var xxx_messageInfo_TestAllTypes proto.InternalMessageInfo

func (m *TestAllTypes) GetSingleInt32() int32 {
	if m != nil {
		return m.SingleInt32
	}
	return 0
}

func (m *TestAllTypes) GetSingleInt64() int64 {
	if m != nil {
		return m.SingleInt64
	}
	return 0
}

func (m *TestAllTypes) GetSingleUint32() uint32 {
	if m != nil {
		return m.SingleUint32
	}
	return 0
}

func (m *TestAllTypes) GetSingleUint64() uint64 {
	if m != nil {
		return m.SingleUint64
	}
	return 0
}

func (m *TestAllTypes) GetSingleSint32() int32 {
	if m != nil {
		return m.SingleSint32
	}
	return 0
}

func (m *TestAllTypes) GetSingleSint64() int64 {
	if m != nil {
		return m.SingleSint64
	}
	return 0
}

func (m *TestAllTypes) GetSingleFixed32() uint32 {
	if m != nil {
		return m.SingleFixed32
	}
	return 0
}

func (m *TestAllTypes) GetSingleFixed64() uint64 {
	if m != nil {
		return m.SingleFixed64
	}
	return 0
}

func (m *TestAllTypes) GetSingleSfixed32() int32 {
	if m != nil {
		return m.SingleSfixed32
	}
	return 0
}

func (m *TestAllTypes) GetSingleSfixed64() int64 {
	if m != nil {
		return m.SingleSfixed64
	}
	return 0
}

func (m *TestAllTypes) GetSingleFloat() float32 {
	if m != nil {
		return m.SingleFloat
	}
	return 0
}

func (m *TestAllTypes) GetSingleDouble() float64 {
	if m != nil {
		return m.SingleDouble
	}
	return 0
}

func (m *TestAllTypes) GetSingleBool() bool {
	if m != nil {
		return m.SingleBool
	}
	return false
}

func (m *TestAllTypes) GetSingleString() string {
	if m != nil {
		return m.SingleString
	}
	return ""
}

func (m *TestAllTypes) GetSingleBytes() []byte {
	if m != nil {
		return m.SingleBytes
	}
	return nil
}

func (m *TestAllTypes) GetSingleAny() *any.Any {
	if m != nil {
		return m.SingleAny
	}
	return nil
}

func (m *TestAllTypes) GetSingleDuration() *duration.Duration {
	if m != nil {
		return m.SingleDuration
	}
	return nil
}

func (m *TestAllTypes) GetSingleTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.SingleTimestamp
	}
	return nil
}

func (m *TestAllTypes) GetSingleStruct() *_struct.Struct {
	if m != nil {
		return m.SingleStruct
	}
	return nil
}

func (m *TestAllTypes) GetSingleValue() *_struct.Value {
	if m != nil {
		return m.SingleValue
	}
	return nil
}

func (m *TestAllTypes) GetSingleInt64Wrapper() *wrappers.Int64Value {
	if m != nil {
		return m.SingleInt64Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleInt32Wrapper() *wrappers.Int32Value {
	if m != nil {
		return m.SingleInt32Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleDoubleWrapper() *wrappers.DoubleValue {
	if m != nil {
		return m.SingleDoubleWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleFloatWrapper() *wrappers.FloatValue {
	if m != nil {
		return m.SingleFloatWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleUint64Wrapper() *wrappers.UInt64Value {
	if m != nil {
		return m.SingleUint64Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleUint32Wrapper() *wrappers.UInt32Value {
	if m != nil {
		return m.SingleUint32Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleStringWrapper() *wrappers.StringValue {
	if m != nil {
		return m.SingleStringWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleBoolWrapper() *wrappers.BoolValue {
	if m != nil {
		return m.SingleBoolWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleBytesWrapper() *wrappers.BytesValue {
	if m != nil {
		return m.SingleBytesWrapper
	}
	return nil
}

type isTestAllTypes_NestedType interface {
	isTestAllTypes_NestedType()
}

type TestAllTypes_SingleNestedMessage struct {
	SingleNestedMessage *TestAllTypes_NestedMessage `protobuf:"bytes,18,opt,name=single_nested_message,json=singleNestedMessage,proto3,oneof"`
}

type TestAllTypes_SingleNestedEnum struct {
	SingleNestedEnum TestAllTypes_NestedEnum `protobuf:"varint,21,opt,name=single_nested_enum,json=singleNestedEnum,proto3,enum=google.expr.proto3.test.TestAllTypes_NestedEnum,oneof"`
}

func (*TestAllTypes_SingleNestedMessage) isTestAllTypes_NestedType() {}

func (*TestAllTypes_SingleNestedEnum) isTestAllTypes_NestedType() {}

func (m *TestAllTypes) GetNestedType() isTestAllTypes_NestedType {
	if m != nil {
		return m.NestedType
	}
	return nil
}

func (m *TestAllTypes) GetSingleNestedMessage() *TestAllTypes_NestedMessage {
	if x, ok := m.GetNestedType().(*TestAllTypes_SingleNestedMessage); ok {
		return x.SingleNestedMessage
	}
	return nil
}

func (m *TestAllTypes) GetSingleNestedEnum() TestAllTypes_NestedEnum {
	if x, ok := m.GetNestedType().(*TestAllTypes_SingleNestedEnum); ok {
		return x.SingleNestedEnum
	}
	return TestAllTypes_FOO
}

func (m *TestAllTypes) GetRepeatedInt32() []int32 {
	if m != nil {
		return m.RepeatedInt32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedInt64() []int64 {
	if m != nil {
		return m.RepeatedInt64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedUint32() []uint32 {
	if m != nil {
		return m.RepeatedUint32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedUint64() []uint64 {
	if m != nil {
		return m.RepeatedUint64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSint32() []int32 {
	if m != nil {
		return m.RepeatedSint32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSint64() []int64 {
	if m != nil {
		return m.RepeatedSint64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedFixed32() []uint32 {
	if m != nil {
		return m.RepeatedFixed32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedFixed64() []uint64 {
	if m != nil {
		return m.RepeatedFixed64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSfixed32() []int32 {
	if m != nil {
		return m.RepeatedSfixed32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSfixed64() []int64 {
	if m != nil {
		return m.RepeatedSfixed64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedFloat() []float32 {
	if m != nil {
		return m.RepeatedFloat
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedDouble() []float64 {
	if m != nil {
		return m.RepeatedDouble
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedBool() []bool {
	if m != nil {
		return m.RepeatedBool
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedString() []string {
	if m != nil {
		return m.RepeatedString
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedBytes() [][]byte {
	if m != nil {
		return m.RepeatedBytes
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedNestedMessage() []*TestAllTypes_NestedMessage {
	if m != nil {
		return m.RepeatedNestedMessage
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedNestedEnum() []TestAllTypes_NestedEnum {
	if m != nil {
		return m.RepeatedNestedEnum
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedStringPiece() []string {
	if m != nil {
		return m.RepeatedStringPiece
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedCord() []string {
	if m != nil {
		return m.RepeatedCord
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedLazyMessage() []*TestAllTypes_NestedMessage {
	if m != nil {
		return m.RepeatedLazyMessage
	}
	return nil
}

func (m *TestAllTypes) GetMapStringString() map[string]string {
	if m != nil {
		return m.MapStringString
	}
	return nil
}

func (m *TestAllTypes) GetMapInt64NestedType() map[int64]*NestedTestAllTypes {
	if m != nil {
		return m.MapInt64NestedType
	}
	return nil
}

func (m *TestAllTypes) GetImportedEnums() []ImportedGlobalEnum {
	if m != nil {
		return m.ImportedEnums
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestAllTypes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestAllTypes_SingleNestedMessage)(nil),
		(*TestAllTypes_SingleNestedEnum)(nil),
	}
}

type TestAllTypes_NestedMessage struct {
	Bb                   int32    `protobuf:"varint,1,opt,name=bb,proto3" json:"bb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAllTypes_NestedMessage) Reset()         { *m = TestAllTypes_NestedMessage{} }
func (m *TestAllTypes_NestedMessage) String() string { return proto.CompactTextString(m) }
func (*TestAllTypes_NestedMessage) ProtoMessage()    {}
func (*TestAllTypes_NestedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a94cd3b88bedc6, []int{0, 0}
}

func (m *TestAllTypes_NestedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAllTypes_NestedMessage.Unmarshal(m, b)
}
func (m *TestAllTypes_NestedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAllTypes_NestedMessage.Marshal(b, m, deterministic)
}
func (m *TestAllTypes_NestedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAllTypes_NestedMessage.Merge(m, src)
}
func (m *TestAllTypes_NestedMessage) XXX_Size() int {
	return xxx_messageInfo_TestAllTypes_NestedMessage.Size(m)
}
func (m *TestAllTypes_NestedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAllTypes_NestedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestAllTypes_NestedMessage proto.InternalMessageInfo

func (m *TestAllTypes_NestedMessage) GetBb() int32 {
	if m != nil {
		return m.Bb
	}
	return 0
}

type NestedTestAllTypes struct {
	Child                *NestedTestAllTypes `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	Payload              *TestAllTypes       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NestedTestAllTypes) Reset()         { *m = NestedTestAllTypes{} }
func (m *NestedTestAllTypes) String() string { return proto.CompactTextString(m) }
func (*NestedTestAllTypes) ProtoMessage()    {}
func (*NestedTestAllTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a94cd3b88bedc6, []int{1}
}

func (m *NestedTestAllTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedTestAllTypes.Unmarshal(m, b)
}
func (m *NestedTestAllTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedTestAllTypes.Marshal(b, m, deterministic)
}
func (m *NestedTestAllTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedTestAllTypes.Merge(m, src)
}
func (m *NestedTestAllTypes) XXX_Size() int {
	return xxx_messageInfo_NestedTestAllTypes.Size(m)
}
func (m *NestedTestAllTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedTestAllTypes.DiscardUnknown(m)
}

var xxx_messageInfo_NestedTestAllTypes proto.InternalMessageInfo

func (m *NestedTestAllTypes) GetChild() *NestedTestAllTypes {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *NestedTestAllTypes) GetPayload() *TestAllTypes {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.expr.proto3.test.GlobalEnum", GlobalEnum_name, GlobalEnum_value)
	proto.RegisterEnum("google.expr.proto3.test.TestAllTypes_NestedEnum", TestAllTypes_NestedEnum_name, TestAllTypes_NestedEnum_value)
	proto.RegisterType((*TestAllTypes)(nil), "google.expr.proto3.test.TestAllTypes")
	proto.RegisterMapType((map[int64]*NestedTestAllTypes)(nil), "google.expr.proto3.test.TestAllTypes.MapInt64NestedTypeEntry")
	proto.RegisterMapType((map[string]string)(nil), "google.expr.proto3.test.TestAllTypes.MapStringStringEntry")
	proto.RegisterType((*TestAllTypes_NestedMessage)(nil), "google.expr.proto3.test.TestAllTypes.NestedMessage")
	proto.RegisterType((*NestedTestAllTypes)(nil), "google.expr.proto3.test.NestedTestAllTypes")
}

func init() { proto.RegisterFile("test/proto3pb/test_all_types.proto", fileDescriptor_12a94cd3b88bedc6) }

var fileDescriptor_12a94cd3b88bedc6 = []byte{
	// 1312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x6d, 0x73, 0xd3, 0x46,
	0x10, 0xe6, 0x2c, 0xf2, 0x76, 0xb1, 0x13, 0xe7, 0x92, 0x34, 0x87, 0xcb, 0x34, 0x47, 0x28, 0xe4,
	0x80, 0xe2, 0x30, 0xb6, 0x46, 0x2d, 0x94, 0x4e, 0x27, 0x2e, 0x10, 0xe8, 0x94, 0xc2, 0x28, 0xd0,
	0xce, 0xf0, 0xc5, 0x95, 0xec, 0x8b, 0x51, 0x23, 0x4b, 0xaa, 0x5e, 0x5a, 0xcc, 0x2f, 0xe9, 0x0f,
	0xeb, 0x0f, 0xea, 0xe8, 0x5e, 0xe4, 0x93, 0x84, 0x19, 0xc8, 0x97, 0x8c, 0xb5, 0xf7, 0xec, 0xb3,
	0xbb, 0xcf, 0xed, 0x6a, 0x23, 0x78, 0x90, 0xb2, 0x24, 0x3d, 0x8a, 0xe2, 0x30, 0x0d, 0xfb, 0x91,
	0x7b, 0x94, 0x3f, 0x0d, 0x1d, 0xdf, 0x1f, 0xa6, 0xb3, 0x88, 0x25, 0x5d, 0x6e, 0x47, 0x7b, 0x93,
	0x30, 0x9c, 0xf8, 0xac, 0xcb, 0xde, 0x45, 0xb1, 0x30, 0xf5, 0xbb, 0x39, 0xb0, 0x73, 0x45, 0x1c,
	0x08, 0x77, 0x37, 0x3b, 0x3b, 0x72, 0x82, 0x99, 0x00, 0x74, 0xbe, 0xaa, 0x1e, 0x8d, 0xb3, 0xd8,
	0x49, 0xbd, 0x30, 0x90, 0xe7, 0x57, 0xab, 0xe7, 0x49, 0x1a, 0x67, 0xa3, 0x54, 0x9e, 0xee, 0x57,
	0x4f, 0x53, 0x6f, 0xca, 0x92, 0xd4, 0x99, 0x46, 0x8b, 0xe8, 0xff, 0x89, 0x9d, 0x28, 0x62, 0x71,
	0xa2, 0x08, 0x3e, 0x50, 0x96, 0x37, 0x8d, 0xc2, 0x58, 0x46, 0x38, 0xf8, 0xaf, 0x03, 0x9b, 0xaf,
	0x58, 0x92, 0x1e, 0xfb, 0xfe, 0xab, 0xbc, 0x54, 0x74, 0x0d, 0x36, 0x13, 0x2f, 0x98, 0xf8, 0x6c,
	0xe8, 0x05, 0x69, 0xbf, 0x87, 0x01, 0x01, 0x74, 0xc9, 0x5e, 0x17, 0xb6, 0x67, 0xb9, 0xa9, 0x0c,
	0xb1, 0x4c, 0xdc, 0x20, 0x80, 0x1a, 0x1a, 0xc4, 0x32, 0xd1, 0x75, 0xd8, 0x92, 0x90, 0x4c, 0xd0,
	0x18, 0x04, 0xd0, 0x96, 0x2d, 0xfd, 0x5e, 0x73, 0x5b, 0x05, 0x64, 0x99, 0xf8, 0x32, 0x01, 0xf4,
	0xb2, 0x0e, 0x2a, 0x31, 0x25, 0x82, 0x69, 0x89, 0x00, 0xba, 0xa5, 0x40, 0xa7, 0x55, 0xa6, 0x44,
	0x30, 0x2d, 0x13, 0x40, 0x91, 0x0e, 0xb2, 0x4c, 0x74, 0x03, 0x6e, 0x48, 0xd0, 0x99, 0xf7, 0x8e,
	0x8d, 0xfb, 0x3d, 0xbc, 0x42, 0x00, 0x5d, 0xb1, 0xa5, 0xeb, 0x13, 0x61, 0xac, 0xc2, 0x2c, 0x13,
	0xaf, 0x12, 0x40, 0x97, 0x4b, 0x30, 0xcb, 0x44, 0x87, 0x70, 0x53, 0x85, 0x54, 0x74, 0x6b, 0x04,
	0xd0, 0x4d, 0x5b, 0x7a, 0x9f, 0x4a, 0x6b, 0x0d, 0x68, 0x99, 0x18, 0x12, 0x40, 0xdb, 0x65, 0xa0,
	0x65, 0x6a, 0xb2, 0x9e, 0xf9, 0xa1, 0x93, 0xe2, 0x75, 0x02, 0x68, 0x43, 0xc9, 0xfa, 0x24, 0x37,
	0x69, 0x75, 0x8e, 0xc3, 0xcc, 0xf5, 0x19, 0x6e, 0x12, 0x40, 0x81, 0xaa, 0xf3, 0x11, 0xb7, 0xa1,
	0x7d, 0x28, 0x7d, 0x86, 0x6e, 0x18, 0xfa, 0xb8, 0x45, 0x00, 0x5d, 0xb5, 0xa1, 0x30, 0x0d, 0xc2,
	0xd0, 0xd7, 0xd5, 0x4a, 0x63, 0x2f, 0x98, 0xe0, 0x0d, 0x02, 0xe8, 0x5a, 0xa1, 0x16, 0xb7, 0x69,
	0xd9, 0xb8, 0xb3, 0x94, 0x25, 0x78, 0x93, 0x00, 0xda, 0x54, 0xd9, 0x0c, 0x72, 0x13, 0xea, 0x43,
	0xc9, 0x3a, 0x74, 0x82, 0x19, 0x1e, 0x13, 0x40, 0xd7, 0x7b, 0x3b, 0x5d, 0x39, 0x24, 0xaa, 0x23,
	0xbb, 0xc7, 0xc1, 0xcc, 0x5e, 0x13, 0xb8, 0xe3, 0x60, 0x86, 0x06, 0x85, 0x1c, 0x6a, 0x12, 0x30,
	0xe3, 0x9e, 0x57, 0x6a, 0x9e, 0x8f, 0x24, 0x40, 0x29, 0xa5, 0x9e, 0xd1, 0x63, 0xd8, 0x96, 0x1c,
	0xc5, 0x3c, 0xe0, 0x33, 0x4e, 0xd2, 0xa9, 0x91, 0xbc, 0x52, 0x08, 0x5b, 0xc6, 0x2d, 0x0c, 0xe8,
	0xa1, 0xae, 0x43, 0x36, 0x4a, 0xf1, 0x84, 0x73, 0xec, 0xd5, 0x38, 0x4e, 0xf9, 0xb1, 0x26, 0x50,
	0x36, 0x4a, 0xd1, 0xfd, 0x42, 0xa0, 0xbf, 0x1d, 0x3f, 0x63, 0xf8, 0x2d, 0x77, 0xfe, 0xa2, 0xe6,
	0xfc, 0x5b, 0x7e, 0xaa, 0x84, 0xe3, 0x0f, 0xe8, 0x39, 0xdc, 0xd1, 0x07, 0x68, 0x28, 0x87, 0x16,
	0x7b, 0x9c, 0xe2, 0xcb, 0x1a, 0x05, 0x9f, 0x29, 0xc1, 0x83, 0xb4, 0x29, 0xfb, 0x5d, 0xb8, 0x95,
	0xe9, 0xfa, 0xbd, 0x82, 0xee, 0xcf, 0xc5, 0x74, 0xfd, 0x5e, 0x95, 0xae, 0xdf, 0x53, 0x74, 0x2f,
	0xe1, 0x6e, 0xa9, 0xc9, 0x0a, 0xbe, 0x73, 0xce, 0x77, 0xb5, 0x7e, 0x4f, 0x1c, 0x26, 0x08, 0xb7,
	0xf5, 0x56, 0xac, 0x27, 0xc8, 0x3b, 0xbb, 0x20, 0xf4, 0x17, 0x24, 0xc8, 0x9b, 0xbd, 0x94, 0x20,
	0xb7, 0xd4, 0x13, 0xcc, 0xca, 0xfa, 0x4d, 0x17, 0x24, 0xf8, 0x5a, 0x13, 0x70, 0x5b, 0x7f, 0xbb,
	0x7c, 0x98, 0x51, 0x93, 0x30, 0xf8, 0x08, 0xa3, 0xd2, 0x70, 0x5b, 0x7f, 0xa9, 0xd5, 0x19, 0xc5,
	0x8c, 0x15, 0x8c, 0xe1, 0x02, 0x46, 0x31, 0x76, 0x25, 0x46, 0x61, 0x52, 0x8c, 0x3f, 0xc3, 0x6d,
	0x6d, 0xac, 0x0b, 0xbe, 0x68, 0x41, 0xdf, 0xe7, 0x93, 0x2e, 0xd8, 0xb6, 0xe6, 0xa3, 0x5f, 0xbf,
	0x10, 0x3e, 0xdc, 0x05, 0xd9, 0x5f, 0x0b, 0x2e, 0x84, 0xcf, 0x7b, 0xe9, 0x42, 0xb8, 0x45, 0xd1,
	0x79, 0x45, 0xb1, 0x01, 0x4b, 0x52, 0x36, 0x1e, 0x4e, 0x59, 0x92, 0x38, 0x13, 0x86, 0x11, 0xe7,
	0xeb, 0x77, 0x17, 0x2c, 0xce, 0xae, 0xbe, 0x79, 0xba, 0xbf, 0x72, 0xdf, 0xe7, 0xc2, 0xf5, 0xe9,
	0x25, 0xa5, 0x42, 0xc9, 0x8c, 0xfe, 0x80, 0xa8, 0x1c, 0x8a, 0x05, 0xd9, 0x14, 0xef, 0x12, 0x40,
	0x37, 0x7a, 0xf7, 0x3e, 0x27, 0xce, 0xe3, 0x20, 0x9b, 0x3e, 0xbd, 0x64, 0xb7, 0xf5, 0x20, 0xb9,
	0x2d, 0x7f, 0xff, 0xc7, 0x2c, 0x62, 0x4e, 0x4e, 0x2e, 0x36, 0xce, 0x3e, 0x31, 0xe8, 0x92, 0xdd,
	0x52, 0x56, 0xb1, 0x04, 0x2b, 0x30, 0xcb, 0xc4, 0x84, 0x18, 0xd4, 0x28, 0xc1, 0xc4, 0x9a, 0x28,
	0x60, 0x72, 0x15, 0x5e, 0x23, 0x06, 0x6d, 0xd9, 0x85, 0xb7, 0x5c, 0x86, 0x55, 0xa0, 0x65, 0xe2,
	0x03, 0x62, 0xd0, 0xcb, 0x65, 0x60, 0x85, 0x51, 0xae, 0xc4, 0xeb, 0xc4, 0xa0, 0x5b, 0x73, 0xe0,
	0x69, 0x9d, 0x51, 0xae, 0xc5, 0xaf, 0x89, 0x41, 0x51, 0x19, 0x68, 0x99, 0xe8, 0x16, 0x6c, 0x17,
	0x40, 0xb5, 0xcb, 0x6e, 0x10, 0x83, 0xae, 0xd8, 0x05, 0x81, 0x5a, 0x8e, 0x35, 0xa8, 0x65, 0xe2,
	0x9b, 0xc4, 0xa0, 0xcb, 0x15, 0xa8, 0x65, 0xa2, 0x3b, 0x70, 0x6b, 0x1e, 0x5e, 0xd1, 0x1e, 0x12,
	0x83, 0x6e, 0xda, 0x05, 0x47, 0xb1, 0x24, 0xeb, 0x60, 0xcb, 0xc4, 0x94, 0x18, 0xb4, 0x5d, 0x05,
	0x8b, 0x45, 0x3e, 0x4f, 0x82, 0xaf, 0xca, 0x5b, 0xc4, 0xa0, 0x8d, 0xb9, 0xf4, 0x62, 0x59, 0xea,
	0xf5, 0xcb, 0x75, 0x79, 0x9b, 0x18, 0x14, 0xcc, 0xeb, 0x97, 0x0b, 0xf3, 0x3a, 0x2c, 0x3c, 0xc5,
	0xca, 0xbc, 0x43, 0x0c, 0xba, 0x6a, 0x37, 0x95, 0x91, 0x2f, 0xcd, 0x92, 0x9a, 0x62, 0x6d, 0x7e,
	0x43, 0x0c, 0xba, 0xa6, 0xa9, 0x29, 0x16, 0xa7, 0x9e, 0x9d, 0x58, 0x9d, 0x77, 0x89, 0x41, 0x9b,
	0xf3, 0xec, 0xc4, 0xf2, 0x3c, 0x87, 0x7b, 0x05, 0xac, 0x32, 0x35, 0xf7, 0x88, 0x71, 0xc1, 0xa9,
	0xb1, 0x77, 0x15, 0x67, 0x79, 0x6a, 0x5c, 0xb8, 0x53, 0x0d, 0xc6, 0xe7, 0xa6, 0x4f, 0x8c, 0x8b,
	0xcc, 0x8d, 0x8d, 0xca, 0x61, 0xf8, 0xdc, 0x58, 0x70, 0xb7, 0x22, 0xd0, 0x30, 0xf2, 0xd8, 0x88,
	0x61, 0x2b, 0x97, 0x69, 0xd0, 0x58, 0x6d, 0xd8, 0xdb, 0x65, 0xa9, 0x5e, 0xe6, 0xc7, 0xe8, 0x50,
	0x53, 0x7f, 0x14, 0xc6, 0x63, 0xfc, 0xad, 0xc4, 0x83, 0xf9, 0x0d, 0xfc, 0x14, 0xc6, 0x63, 0x74,
	0xae, 0x05, 0xf0, 0x9d, 0xf7, 0xb3, 0x42, 0xaf, 0xfb, 0x17, 0xd6, 0x6b, 0xd0, 0xa0, 0x60, 0x9e,
	0xd5, 0x2f, 0xce, 0xfb, 0x99, 0x52, 0xec, 0x0c, 0x6e, 0x4d, 0x9d, 0x48, 0x15, 0x22, 0x2f, 0xfc,
	0x01, 0x0f, 0xf4, 0xe0, 0xd3, 0x02, 0x3d, 0x77, 0x22, 0x51, 0xa6, 0xf8, 0xfb, 0x38, 0x48, 0xe3,
	0x99, 0xbd, 0x39, 0x2d, 0x5b, 0x51, 0x04, 0x77, 0xf3, 0x38, 0x62, 0x8f, 0xc9, 0xab, 0xc9, 0xbf,
	0x39, 0xf0, 0xf7, 0x3c, 0xd6, 0x0f, 0x9f, 0x1c, 0x8b, 0xbf, 0x6e, 0x44, 0x71, 0xb9, 0x4d, 0x84,
	0x43, 0xd3, 0xda, 0x01, 0xb2, 0xe1, 0x86, 0xf8, 0x02, 0x90, 0x4d, 0x90, 0xe0, 0x87, 0xbc, 0x0b,
	0xee, 0x2c, 0x0c, 0xf5, 0x4c, 0xc2, 0x4f, 0xfc, 0xd0, 0x75, 0x7c, 0xde, 0x00, 0x2d, 0x45, 0x91,
	0x3f, 0x25, 0x9d, 0x7d, 0xd8, 0x2a, 0x37, 0xdc, 0x06, 0x6c, 0xb8, 0xae, 0xfc, 0x76, 0x68, 0xb8,
	0x6e, 0x67, 0x00, 0x77, 0x3e, 0xa4, 0x07, 0x6a, 0x43, 0xe3, 0x9c, 0xcd, 0x38, 0x70, 0xcd, 0xce,
	0x7f, 0xa2, 0x1d, 0xb8, 0x24, 0xfe, 0x9f, 0x6a, 0x70, 0x9b, 0x78, 0x78, 0xd0, 0xf8, 0x0e, 0x74,
	0x62, 0xb8, 0xb7, 0xa0, 0x4e, 0x9d, 0xc6, 0x10, 0x34, 0xc7, 0x3a, 0xcd, 0xfa, 0x47, 0x8a, 0x93,
	0x54, 0x9a, 0x9a, 0x5a, 0xcc, 0x83, 0x43, 0x08, 0xb5, 0x16, 0x5f, 0x81, 0xc6, 0x93, 0x17, 0x2f,
	0xda, 0x97, 0xf2, 0x1f, 0x83, 0x63, 0xbb, 0x0d, 0xc4, 0x8f, 0x37, 0xed, 0xc6, 0xa0, 0x05, 0xd7,
	0xb5, 0xdb, 0x3b, 0xf8, 0x17, 0x40, 0x54, 0x67, 0xce, 0xb3, 0x1a, 0xbd, 0xf5, 0xfc, 0x31, 0xcf,
	0xf4, 0x73, 0xb3, 0xe2, 0x9e, 0xe8, 0x47, 0xb8, 0x12, 0x39, 0x33, 0x3f, 0x74, 0xc6, 0xb2, 0xb4,
	0x1b, 0x9f, 0xd4, 0x22, 0xb6, 0xf2, 0xba, 0x7d, 0x08, 0xe1, 0xfc, 0x22, 0xf3, 0x02, 0x4e, 0x54,
	0x49, 0x27, 0xaa, 0xa4, 0x13, 0x5e, 0x12, 0x7d, 0x73, 0x73, 0xe2, 0xa5, 0x6f, 0x33, 0xb7, 0x3b,
	0x0a, 0xa7, 0x47, 0xf2, 0x43, 0x73, 0xc4, 0xfc, 0xbb, 0x93, 0xf0, 0xa8, 0xf4, 0x59, 0xe9, 0x2e,
	0x8b, 0x5f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xf3, 0x02, 0x4f, 0x45, 0x0f, 0x00, 0x00,
}
