// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package common

import (
	canoncommon "cel.dev/cel-go/common"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

// Type aliases
type (
	Doc            = canoncommon.Doc
	DocKind        = canoncommon.DocKind
	Documentor     = canoncommon.Documentor
	Error          = canoncommon.Error
	Errors         = canoncommon.Errors
	Location       = canoncommon.Location
	Source         = canoncommon.Source
	SourceLocation = canoncommon.SourceLocation
)

// Constants
const (
	ConstCost                   = canoncommon.ConstCost
	DocEnv                      = canoncommon.DocEnv
	DocExample                  = canoncommon.DocExample
	DocField                    = canoncommon.DocField
	DocFunction                 = canoncommon.DocFunction
	DocMacro                    = canoncommon.DocMacro
	DocOverload                 = canoncommon.DocOverload
	DocVariable                 = canoncommon.DocVariable
	ListCreateBaseCost          = canoncommon.ListCreateBaseCost
	MapCreateBaseCost           = canoncommon.MapCreateBaseCost
	RegexStringLengthCostFactor = canoncommon.RegexStringLengthCostFactor
	SelectAndIdentCost          = canoncommon.SelectAndIdentCost
	StringTraversalCostFactor   = canoncommon.StringTraversalCostFactor
	StructCreateBaseCost        = canoncommon.StructCreateBaseCost
)

// Variables
var (
	NoLocation = canoncommon.NoLocation
)

// Functions

func MultilineDescription(lines ...string) string {
	return canoncommon.MultilineDescription(lines...)
}

func NewError(id int64, message string, location Location) *Error {
	return canoncommon.NewError(id, message, location)
}

func NewErrors(source Source) *Errors {
	return canoncommon.NewErrors(source)
}

func NewExampleDoc(ex string) *Doc {
	return canoncommon.NewExampleDoc(ex)
}

func NewFieldDoc(name, celType, description string, examples ...*Doc) *Doc {
	return canoncommon.NewFieldDoc(name, celType, description, examples...)
}

func NewFunctionDoc(name, description string, overloads ...*Doc) *Doc {
	return canoncommon.NewFunctionDoc(name, description, overloads...)
}

func NewInfoSource(info *exprpb.SourceInfo) Source {
	return canoncommon.NewInfoSource(info)
}

func NewLocation(line, column int) Location {
	return canoncommon.NewLocation(line, column)
}

func NewMacroDoc(name, description string, examples ...*Doc) *Doc {
	return canoncommon.NewMacroDoc(name, description, examples...)
}

func NewOverloadDoc(id, signature string, examples ...*Doc) *Doc {
	return canoncommon.NewOverloadDoc(id, signature, examples...)
}

func NewStringSource(contents string, description string) Source {
	return canoncommon.NewStringSource(contents, description)
}

func NewStringSourceWithLimit(contents string, description string, limit int) (Source, error) {
	return canoncommon.NewStringSourceWithLimit(contents, description, limit)
}

func NewTextSource(text string) Source {
	return canoncommon.NewTextSource(text)
}

func NewTextSourceWithLimit(text string, limit int) (Source, error) {
	return canoncommon.NewTextSourceWithLimit(text, limit)
}

func NewVariableDoc(name, celType, description string) *Doc {
	return canoncommon.NewVariableDoc(name, celType, description)
}

func ParseDescription(doc string) string {
	return canoncommon.ParseDescription(doc)
}

func ParseDescriptions(doc string) []string {
	return canoncommon.ParseDescriptions(doc)
}
