// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package cel

import (
	canoncel "cel.dev/cel-go/cel"
	"cel.dev/cel-go/cel/async"
	"cel.dev/cel-go/checker"
	"cel.dev/cel-go/common"
	"cel.dev/cel-go/common/ast"
	celast "cel.dev/cel-go/common/ast"
	"cel.dev/cel-go/common/decls"
	"cel.dev/cel-go/common/env"
	"cel.dev/cel-go/common/functions"
	"cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/ref"
	"cel.dev/cel-go/interpreter"
	celpb "cel.dev/expr"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Type aliases
type (
	ASTOptimizer             = canoncel.ASTOptimizer
	ASTValidator             = canoncel.ASTValidator
	ASTValidatorConfigurer   = canoncel.ASTValidatorConfigurer
	ASTValidatorFactory      = canoncel.ASTValidatorFactory
	Activation               = canoncel.Activation
	Ast                      = canoncel.Ast
	AttributePatternType     = canoncel.AttributePatternType
	ConfigOptionFactory      = canoncel.ConfigOptionFactory
	ConfigurableASTValidator = canoncel.ConfigurableASTValidator
	ConstantFoldingOption    = canoncel.ConstantFoldingOption
	Env                      = canoncel.Env
	EnvOption                = canoncel.EnvOption
	Error                    = canoncel.Error
	EvalDetails              = canoncel.EvalDetails
	EvalOption               = canoncel.EvalOption
	EvalResult               = canoncel.EvalResult
	FunctionOpt              = canoncel.FunctionOpt
	InlineVariable           = canoncel.InlineVariable
	Issues                   = canoncel.Issues
	Kind                     = canoncel.Kind
	Library                  = canoncel.Library
	LibraryAliaser           = canoncel.LibraryAliaser
	LibrarySubsetter         = canoncel.LibrarySubsetter
	LibraryVersioner         = canoncel.LibraryVersioner
	Macro                    = canoncel.Macro
	MacroExpander            = canoncel.MacroExpander
	MacroExprFactory         = canoncel.MacroExprFactory
	MacroExprHelper          = canoncel.MacroExprHelper
	MacroFactory             = canoncel.MacroFactory
	MacroOpt                 = canoncel.MacroOpt
	MutableValidatorConfig   = canoncel.MutableValidatorConfig
	OptimizerContext         = canoncel.OptimizerContext
	OptimizerOption          = canoncel.OptimizerOption
	OptionalTypesOption      = canoncel.OptionalTypesOption
	OverloadOpt              = canoncel.OverloadOpt
	OverloadSelector         = canoncel.OverloadSelector
	PartialActivation        = canoncel.PartialActivation
	Program                  = canoncel.Program
	ProgramOption            = canoncel.ProgramOption
	Prompt                   = canoncel.Prompt
	SingletonLibrary         = canoncel.SingletonLibrary
	Source                   = canoncel.Source
	StaticOptimizer          = canoncel.StaticOptimizer
	StdLibOption             = canoncel.StdLibOption
	Type                     = canoncel.Type
	ValidatorConfig          = canoncel.ValidatorConfig
)

// Constants
const (
	AnyKind                                    = canoncel.AnyKind
	BoolKind                                   = canoncel.BoolKind
	BytesKind                                  = canoncel.BytesKind
	DoubleKind                                 = canoncel.DoubleKind
	DurationKind                               = canoncel.DurationKind
	DynKind                                    = canoncel.DynKind
	HomogeneousAggregateLiteralExemptFunctions = canoncel.HomogeneousAggregateLiteralExemptFunctions
	IntKind                                    = canoncel.IntKind
	ListKind                                   = canoncel.ListKind
	MapKind                                    = canoncel.MapKind
	NullTypeKind                               = canoncel.NullTypeKind
	OpaqueKind                                 = canoncel.OpaqueKind
	OptCheckStringFormat                       = canoncel.OptCheckStringFormat
	OptExhaustiveEval                          = canoncel.OptExhaustiveEval
	OptOptimize                                = canoncel.OptOptimize
	OptPartialEval                             = canoncel.OptPartialEval
	OptTrackCost                               = canoncel.OptTrackCost
	OptTrackState                              = canoncel.OptTrackState
	StringKind                                 = canoncel.StringKind
	StructKind                                 = canoncel.StructKind
	TimestampKind                              = canoncel.TimestampKind
	TypeKind                                   = canoncel.TypeKind
	TypeParamKind                              = canoncel.TypeParamKind
	UintKind                                   = canoncel.UintKind
)

// Variables
var (
	AllMacro       = canoncel.AllMacro
	AnyType        = canoncel.AnyType
	BoolType       = canoncel.BoolType
	BytesType      = canoncel.BytesType
	DoubleType     = canoncel.DoubleType
	DurationType   = canoncel.DurationType
	DynType        = canoncel.DynType
	ExistsMacro    = canoncel.ExistsMacro
	ExistsOneMacro = canoncel.ExistsOneMacro
	FilterMacro    = canoncel.FilterMacro
	HasMacro       = canoncel.HasMacro
	IntType        = canoncel.IntType
	ListType       = canoncel.ListType
	MapFilterMacro = canoncel.MapFilterMacro
	MapMacro       = canoncel.MapMacro
	MapType        = canoncel.MapType
	NoMacros       = canoncel.NoMacros
	NullType       = canoncel.NullType
	NullableType   = canoncel.NullableType
	ObjectType     = canoncel.ObjectType
	OpaqueType     = canoncel.OpaqueType
	OptionalType   = canoncel.OptionalType
	StandardMacros = canoncel.StandardMacros
	StringType     = canoncel.StringType
	TimestampType  = canoncel.TimestampType
	TypeParamType  = canoncel.TypeParamType
	TypeType       = canoncel.TypeType
	UintType       = canoncel.UintType
)

// Functions

func ASTValidators(validators ...ASTValidator) EnvOption {
	return canoncel.ASTValidators(validators...)
}

func Abbrevs(qualifiedNames ...string) EnvOption {
	return canoncel.Abbrevs(qualifiedNames...)
}

func AlphaProtoAsDeclaration(d *exprpb.Decl) (EnvOption, error) {
	return canoncel.AlphaProtoAsDeclaration(d)
}

func AlphaProtoAsValue(adapter types.Adapter, v *exprpb.Value) (ref.Val, error) {
	return canoncel.AlphaProtoAsValue(adapter, v)
}

func AstToCheckedExpr(a *Ast) (*exprpb.CheckedExpr, error) {
	return canoncel.AstToCheckedExpr(a)
}

func AstToParsedExpr(a *Ast) (*exprpb.ParsedExpr, error) {
	return canoncel.AstToParsedExpr(a)
}

func AstToString(a *Ast) (string, error) {
	return canoncel.AstToString(a)
}

func AsyncBinding(fn functions.BlockingAsyncOp) OverloadOpt {
	return canoncel.AsyncBinding(fn)
}

func AsyncCallObserver(observer async.Observer) ProgramOption {
	return canoncel.AsyncCallObserver(observer)
}

func AsyncCompletionBufferSize(size int) ProgramOption {
	return canoncel.AsyncCompletionBufferSize(size)
}

func AsyncMaxConcurrency(maxConcurrency int) ProgramOption {
	return canoncel.AsyncMaxConcurrency(maxConcurrency)
}

func AttributePattern(varName string) *AttributePatternType {
	return canoncel.AttributePattern(varName)
}

func AuthoringPrompt(env *Env) (*Prompt, error) {
	return canoncel.AuthoringPrompt(env)
}

func AuthoringPromptWithFieldPaths(env *Env) (*Prompt, error) {
	return canoncel.AuthoringPromptWithFieldPaths(env)
}

func BinaryBinding(binding functions.BinaryOp) OverloadOpt {
	return canoncel.BinaryBinding(binding)
}

func CheckedExprToAst(checkedExpr *exprpb.CheckedExpr) *Ast {
	return canoncel.CheckedExprToAst(checkedExpr)
}

func CheckedExprToAstWithSource(checkedExpr *exprpb.CheckedExpr, src Source) (*Ast, error) {
	return canoncel.CheckedExprToAstWithSource(checkedExpr, src)
}

func ClearMacros() EnvOption {
	return canoncel.ClearMacros()
}

func Compile(expression string, opts ...EnvOption) (Program, error) {
	return canoncel.Compile(expression, opts...)
}

func ConcurrentDrainStrategy(strategy async.DrainStrategy) ProgramOption {
	return canoncel.ConcurrentDrainStrategy(strategy)
}

func Constant(name string, t *Type, v ref.Val) EnvOption {
	return canoncel.Constant(name, t, v)
}

func Container(name string) EnvOption {
	return canoncel.Container(name)
}

func ContextProtoVars(ctx proto.Message, opts ...types.RegistryOption) (Activation, error) {
	return canoncel.ContextProtoVars(ctx, opts...)
}

func CostEstimatorOptions(costOpts ...checker.CostOption) EnvOption {
	return canoncel.CostEstimatorOptions(costOpts...)
}

func CostLimit(costLimit uint64) ProgramOption {
	return canoncel.CostLimit(costLimit)
}

func CostTrackerOptions(costOpts ...interpreter.CostTrackerOption) ProgramOption {
	return canoncel.CostTrackerOptions(costOpts...)
}

func CostTracking(costEstimator interpreter.ActualCostEstimator) ProgramOption {
	return canoncel.CostTracking(costEstimator)
}

func CrossTypeNumericComparisons(enabled bool) EnvOption {
	return canoncel.CrossTypeNumericComparisons(enabled)
}

func CustomDecorator(dec interpreter.InterpretableDecorator) ProgramOption {
	return canoncel.CustomDecorator(dec)
}

func CustomDecoratorV2(dec interpreter.InterpretableDecoratorV2) ProgramOption {
	return canoncel.CustomDecoratorV2(dec)
}

func CustomTypeAdapter(adapter types.Adapter) EnvOption {
	return canoncel.CustomTypeAdapter(adapter)
}

func CustomTypeProvider(provider any) EnvOption {
	return canoncel.CustomTypeProvider(provider)
}

func Declarations(decls ...*exprpb.Decl) EnvOption {
	return canoncel.Declarations(decls...)
}

func DeclareContextProto(descriptor protoreflect.MessageDescriptor) EnvOption {
	return canoncel.DeclareContextProto(descriptor)
}

func DefaultUTCTimeZone(enabled bool) EnvOption {
	return canoncel.DefaultUTCTimeZone(enabled)
}

func DisableDeclaration(value bool) FunctionOpt {
	return canoncel.DisableDeclaration(value)
}

func EagerlyValidateDeclarations(enabled bool) EnvOption {
	return canoncel.EagerlyValidateDeclarations(enabled)
}

func EnableErrorOnBadPresenceTest(value bool) EnvOption {
	return canoncel.EnableErrorOnBadPresenceTest(value)
}

func EnableHiddenAccumulatorName(enabled bool) EnvOption {
	return canoncel.EnableHiddenAccumulatorName(enabled)
}

func EnableIdentifierEscapeSyntax() EnvOption {
	return canoncel.EnableIdentifierEscapeSyntax()
}

func EnableMacroCallTracking() EnvOption {
	return canoncel.EnableMacroCallTracking()
}

func ErrorAsIssues(err error) *Issues {
	return canoncel.ErrorAsIssues(err)
}

func EvalOptions(opts ...EvalOption) ProgramOption {
	return canoncel.EvalOptions(opts...)
}

func ExcludeOverloads(overloadIDs ...string) OverloadSelector {
	return canoncel.ExcludeOverloads(overloadIDs...)
}

func ExistsMacroExpander(meh MacroExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *Error) {
	return canoncel.ExistsMacroExpander(meh, target, args)
}

func ExistsOneMacroExpander(meh MacroExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *Error) {
	return canoncel.ExistsOneMacroExpander(meh, target, args)
}

func ExprDeclToDeclaration(d *exprpb.Decl) (EnvOption, error) {
	return canoncel.ExprDeclToDeclaration(d)
}

func ExprToString(e ast.Expr, info *ast.SourceInfo) (string, error) {
	return canoncel.ExprToString(e, info)
}

func ExprTypeToType(t *exprpb.Type) (*Type, error) {
	return canoncel.ExprTypeToType(t)
}

func ExprValueAsAlphaProto(res ref.Val) (*exprpb.ExprValue, error) {
	return canoncel.ExprValueAsAlphaProto(res)
}

func ExprValueAsProto(res ref.Val) (*celpb.ExprValue, error) {
	return canoncel.ExprValueAsProto(res)
}

func ExpressionNestingDepthLimit(limit int) EnvOption {
	return canoncel.ExpressionNestingDepthLimit(limit)
}

func ExpressionNodeLimit(limit int) EnvOption {
	return canoncel.ExpressionNodeLimit(limit)
}

func ExtendedValidations() EnvOption {
	return canoncel.ExtendedValidations()
}

func FilterMacroExpander(meh MacroExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *Error) {
	return canoncel.FilterMacroExpander(meh, target, args)
}

func FoldKnownValues(knownValues Activation) ConstantFoldingOption {
	return canoncel.FoldKnownValues(knownValues)
}

func FormatCELType(t *Type) string {
	return canoncel.FormatCELType(t)
}

func FormatType(t *exprpb.Type) string {
	return canoncel.FormatType(t)
}

func FromConfig(config *env.Config, optFactories ...ConfigOptionFactory) EnvOption {
	return canoncel.FromConfig(config, optFactories...)
}

func Function(name string, opts ...FunctionOpt) EnvOption {
	return canoncel.Function(name, opts...)
}

func FunctionBinding(binding functions.FunctionOp) OverloadOpt {
	return canoncel.FunctionBinding(binding)
}

func FunctionDecls(funcs ...*decls.FunctionDecl) EnvOption {
	return canoncel.FunctionDecls(funcs...)
}

func FunctionDocs(docs ...string) FunctionOpt {
	return canoncel.FunctionDocs(docs...)
}

func Functions(funcs ...*functions.Overload) ProgramOption {
	return canoncel.Functions(funcs...)
}

func GlobalMacro(function string, argCount int, factory MacroFactory, opts ...MacroOpt) Macro {
	return canoncel.GlobalMacro(function, argCount, factory, opts...)
}

func GlobalVarArgMacro(function string, factory MacroFactory, opts ...MacroOpt) Macro {
	return canoncel.GlobalVarArgMacro(function, factory, opts...)
}

func Globals(vars any) ProgramOption {
	return canoncel.Globals(vars)
}

func HasMacroExpander(meh MacroExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *Error) {
	return canoncel.HasMacroExpander(meh, target, args)
}

func HomogeneousAggregateLiterals() EnvOption {
	return canoncel.HomogeneousAggregateLiterals()
}

func IncludeOverloads(overloadIDs ...string) OverloadSelector {
	return canoncel.IncludeOverloads(overloadIDs...)
}

func InterruptCheckFrequency(checkFrequency uint) ProgramOption {
	return canoncel.InterruptCheckFrequency(checkFrequency)
}

func JSONFieldNames(enabled bool) EnvOption {
	return canoncel.JSONFieldNames(enabled)
}

func LateFunctionBinding() OverloadOpt {
	return canoncel.LateFunctionBinding()
}

func Lib(l Library) EnvOption {
	return canoncel.Lib(l)
}

func MacroDocs(docs ...string) MacroOpt {
	return canoncel.MacroDocs(docs...)
}

func MacroExamples(examples ...string) MacroOpt {
	return canoncel.MacroExamples(examples...)
}

func Macros(macros ...Macro) EnvOption {
	return canoncel.Macros(macros...)
}

func MapMacroExpander(meh MacroExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *Error) {
	return canoncel.MapMacroExpander(meh, target, args)
}

func MaxConstantFoldIterations(limit int) ConstantFoldingOption {
	return canoncel.MaxConstantFoldIterations(limit)
}

func MemberOverload(overloadID string, args []*Type, resultType *Type, opts ...OverloadOpt) FunctionOpt {
	return canoncel.MemberOverload(overloadID, args, resultType, opts...)
}

func NewActivation(bindings any) (Activation, error) {
	return canoncel.NewActivation(bindings)
}

func NewConstantFoldingOptimizer(opts ...ConstantFoldingOption) (ASTOptimizer, error) {
	return canoncel.NewConstantFoldingOptimizer(opts...)
}

func NewCustomEnv(opts ...EnvOption) (*Env, error) {
	return canoncel.NewCustomEnv(opts...)
}

func NewEnv(opts ...EnvOption) (*Env, error) {
	return canoncel.NewEnv(opts...)
}

func NewGlobalMacro(function string, argCount int, expander MacroExpander) Macro {
	return canoncel.NewGlobalMacro(function, argCount, expander)
}

func NewGlobalVarArgMacro(function string, expander MacroExpander) Macro {
	return canoncel.NewGlobalVarArgMacro(function, expander)
}

func NewInlineVariable(name string, definition *Ast) *InlineVariable {
	return canoncel.NewInlineVariable(name, definition)
}

func NewInlineVariableWithAlias(name, alias string, definition *Ast) *InlineVariable {
	return canoncel.NewInlineVariableWithAlias(name, alias, definition)
}

func NewInliningOptimizer(inlineVars ...*InlineVariable) ASTOptimizer {
	return canoncel.NewInliningOptimizer(inlineVars...)
}

func NewIssues(errs *common.Errors) *Issues {
	return canoncel.NewIssues(errs)
}

func NewIssuesWithSourceInfo(errs *common.Errors, info *celast.SourceInfo) *Issues {
	return canoncel.NewIssuesWithSourceInfo(errs, info)
}

func NewReceiverMacro(function string, argCount int, expander MacroExpander) Macro {
	return canoncel.NewReceiverMacro(function, argCount, expander)
}

func NewReceiverVarArgMacro(function string, expander MacroExpander) Macro {
	return canoncel.NewReceiverVarArgMacro(function, expander)
}

func NewStaticOptimizer(options ...any) (*StaticOptimizer, error) {
	return canoncel.NewStaticOptimizer(options...)
}

func NoVars() Activation {
	return canoncel.NoVars()
}

func OptimizeRegex(regexOptimizations ...*interpreter.RegexOptimization) ProgramOption {
	return canoncel.OptimizeRegex(regexOptimizations...)
}

func OptimizeWithSource(source Source) OptimizerOption {
	return canoncel.OptimizeWithSource(source)
}

func OptionalTypes(opts ...OptionalTypesOption) EnvOption {
	return canoncel.OptionalTypes(opts...)
}

func OptionalTypesVersion(version uint32) OptionalTypesOption {
	return canoncel.OptionalTypesVersion(version)
}

func Overload(overloadID string, args []*Type, resultType *Type, opts ...OverloadOpt) FunctionOpt {
	return canoncel.Overload(overloadID, args, resultType, opts...)
}

func OverloadExamples(docs ...string) OverloadOpt {
	return canoncel.OverloadExamples(docs...)
}

func OverloadIsNonStrict() OverloadOpt {
	return canoncel.OverloadIsNonStrict()
}

func OverloadOperandTrait(trait int) OverloadOpt {
	return canoncel.OverloadOperandTrait(trait)
}

func ParsedExprToAst(parsedExpr *exprpb.ParsedExpr) *Ast {
	return canoncel.ParsedExprToAst(parsedExpr)
}

func ParsedExprToAstWithSource(parsedExpr *exprpb.ParsedExpr, src Source) *Ast {
	return canoncel.ParsedExprToAstWithSource(parsedExpr, src)
}

func ParserErrorRecoveryLimit(limit int) EnvOption {
	return canoncel.ParserErrorRecoveryLimit(limit)
}

func ParserExpressionSizeLimit(limit int) EnvOption {
	return canoncel.ParserExpressionSizeLimit(limit)
}

func ParserRecursionLimit(limit int) EnvOption {
	return canoncel.ParserRecursionLimit(limit)
}

func PartialVars(vars any,
	unknowns ...*AttributePatternType) (PartialActivation, error) {
	return canoncel.PartialVars(vars, unknowns...)
}

func ProtoAsDeclaration(d *celpb.Decl) (EnvOption, error) {
	return canoncel.ProtoAsDeclaration(d)
}

func ProtoAsValue(adapter types.Adapter, v *celpb.Value) (ref.Val, error) {
	return canoncel.ProtoAsValue(adapter, v)
}

func ReceiverMacro(function string, argCount int, factory MacroFactory, opts ...MacroOpt) Macro {
	return canoncel.ReceiverMacro(function, argCount, factory, opts...)
}

func ReceiverVarArgMacro(function string, factory MacroFactory, opts ...MacroOpt) Macro {
	return canoncel.ReceiverVarArgMacro(function, factory, opts...)
}

func RefValToExprValue(res ref.Val) (*exprpb.ExprValue, error) {
	return canoncel.RefValToExprValue(res)
}

func RefValueToValue(res ref.Val) (*exprpb.Value, error) {
	return canoncel.RefValueToValue(res)
}

func RegexProgramSizeLimit(limit int) EnvOption {
	return canoncel.RegexProgramSizeLimit(limit)
}

func SingletonAsyncBinding(fn functions.BlockingAsyncOp, traits ...int) FunctionOpt {
	return canoncel.SingletonAsyncBinding(fn, traits...)
}

func SingletonBinaryBinding(fn functions.BinaryOp, traits ...int) FunctionOpt {
	return canoncel.SingletonBinaryBinding(fn, traits...)
}

func SingletonBinaryImpl(fn functions.BinaryOp, traits ...int) FunctionOpt {
	return canoncel.SingletonBinaryImpl(fn, traits...)
}

func SingletonFunctionBinding(fn functions.FunctionOp, traits ...int) FunctionOpt {
	return canoncel.SingletonFunctionBinding(fn, traits...)
}

func SingletonFunctionImpl(fn functions.FunctionOp, traits ...int) FunctionOpt {
	return canoncel.SingletonFunctionImpl(fn, traits...)
}

func SingletonUnaryBinding(fn functions.UnaryOp, traits ...int) FunctionOpt {
	return canoncel.SingletonUnaryBinding(fn, traits...)
}

func StdLib(opts ...StdLibOption) EnvOption {
	return canoncel.StdLib(opts...)
}

func StdLibSubset(subset *env.LibrarySubset) StdLibOption {
	return canoncel.StdLibSubset(subset)
}

func TypeDescs(descs ...any) EnvOption {
	return canoncel.TypeDescs(descs...)
}

func TypeToExprType(t *Type) (*exprpb.Type, error) {
	return canoncel.TypeToExprType(t)
}

func Types(addTypes ...any) EnvOption {
	return canoncel.Types(addTypes...)
}

func UnaryBinding(binding functions.UnaryOp) OverloadOpt {
	return canoncel.UnaryBinding(binding)
}

func ValidateBindNestingLimit(limit int) ASTValidator {
	return canoncel.ValidateBindNestingLimit(limit)
}

func ValidateComprehensionNestingLimit(limit int) ASTValidator {
	return canoncel.ValidateComprehensionNestingLimit(limit)
}

func ValidateDurationLiterals() ASTValidator {
	return canoncel.ValidateDurationLiterals()
}

func ValidateHomogeneousAggregateLiterals() ASTValidator {
	return canoncel.ValidateHomogeneousAggregateLiterals()
}

func ValidateRegexLiterals() ASTValidator {
	return canoncel.ValidateRegexLiterals()
}

func ValidateRegexProgramSizeLimit(limit int) ASTValidator {
	return canoncel.ValidateRegexProgramSizeLimit(limit)
}

func ValidateTimestampLiterals() ASTValidator {
	return canoncel.ValidateTimestampLiterals()
}

func ValueAsAlphaProto(res ref.Val) (*exprpb.Value, error) {
	return canoncel.ValueAsAlphaProto(res)
}

func ValueAsProto(res ref.Val) (*celpb.Value, error) {
	return canoncel.ValueAsProto(res)
}

func ValueToRefValue(adapter types.Adapter, v *exprpb.Value) (ref.Val, error) {
	return canoncel.ValueToRefValue(adapter, v)
}

func Variable(name string, t *Type) EnvOption {
	return canoncel.Variable(name, t)
}

func VariableDecls(vars ...*decls.VariableDecl) EnvOption {
	return canoncel.VariableDecls(vars...)
}

func VariableWithDoc(name string, t *Type, doc string) EnvOption {
	return canoncel.VariableWithDoc(name, t, doc)
}
