// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package interpreter

import (
	"cel.dev/cel-go/common/ast"
	"cel.dev/cel-go/common/containers"
	"cel.dev/cel-go/common/functions"
	"cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/ref"
	canoninterpreter "cel.dev/cel-go/interpreter"
)

// Type aliases
type (
	Activation                = canoninterpreter.Activation
	ActualCostEstimator       = canoninterpreter.ActualCostEstimator
	AsyncCall                 = canoninterpreter.AsyncCall
	AsyncObserver             = canoninterpreter.AsyncObserver
	AttrFactoryOption         = canoninterpreter.AttrFactoryOption
	Attribute                 = canoninterpreter.Attribute
	AttributeFactory          = canoninterpreter.AttributeFactory
	AttributePattern          = canoninterpreter.AttributePattern
	AttributeQualifierPattern = canoninterpreter.AttributeQualifierPattern
	CancellationCause         = canoninterpreter.CancellationCause
	ConstantQualifier         = canoninterpreter.ConstantQualifier
	CostTracker               = canoninterpreter.CostTracker
	CostTrackerOption         = canoninterpreter.CostTrackerOption
	Dispatcher                = canoninterpreter.Dispatcher
	EvalCancelledError        = canoninterpreter.EvalCancelledError
	EvalObserver              = canoninterpreter.EvalObserver
	EvalState                 = canoninterpreter.EvalState
	ExecutionFrame            = canoninterpreter.ExecutionFrame
	FunctionTracker           = canoninterpreter.FunctionTracker
	Interpretable             = canoninterpreter.Interpretable
	InterpretableAttribute    = canoninterpreter.InterpretableAttribute
	InterpretableCall         = canoninterpreter.InterpretableCall
	InterpretableConst        = canoninterpreter.InterpretableConst
	InterpretableConstructor  = canoninterpreter.InterpretableConstructor
	InterpretableDecorator    = canoninterpreter.InterpretableDecorator
	InterpretableDecoratorV2  = canoninterpreter.InterpretableDecoratorV2
	InterpretableV2           = canoninterpreter.InterpretableV2
	Interpreter               = canoninterpreter.Interpreter
	InterruptError            = canoninterpreter.InterruptError
	NamespacedAttribute       = canoninterpreter.NamespacedAttribute
	ObservableInterpretable   = canoninterpreter.ObservableInterpretable
	PartialActivation         = canoninterpreter.PartialActivation
	PlannerOption             = canoninterpreter.PlannerOption
	Qualifier                 = canoninterpreter.Qualifier
	RegexOptimization         = canoninterpreter.RegexOptimization
	StatefulObserver          = canoninterpreter.StatefulObserver
)

// Constants
const (
	ContextCancelled  = canoninterpreter.ContextCancelled
	CostLimitExceeded = canoninterpreter.CostLimitExceeded
)

// Variables
var (
	MatchesRegexOptimization = canoninterpreter.MatchesRegexOptimization
)

// Functions
var (
	CostObserver       = canoninterpreter.CostObserver
	CostTrackerFactory = canoninterpreter.CostTrackerFactory
	EvalStateFactory   = canoninterpreter.EvalStateFactory
	EvalStateObserver  = canoninterpreter.EvalStateObserver
)

func AsFrame(a Activation) *ExecutionFrame {
	return canoninterpreter.AsFrame(a)
}

func AsPartialActivation(vars Activation) (PartialActivation, bool) {
	return canoninterpreter.AsPartialActivation(vars)
}

func CompileRegexConstants(regexOptimizations ...*RegexOptimization) PlannerOption {
	return canoninterpreter.CompileRegexConstants(regexOptimizations...)
}

func CostTrackerLimit(limit uint64) CostTrackerOption {
	return canoninterpreter.CostTrackerLimit(limit)
}

func CustomDecorator(dec InterpretableDecorator) PlannerOption {
	return canoninterpreter.CustomDecorator(dec)
}

func CustomDecoratorV2(dec InterpretableDecoratorV2) PlannerOption {
	return canoninterpreter.CustomDecoratorV2(dec)
}

func EmptyActivation() Activation {
	return canoninterpreter.EmptyActivation()
}

func EnableErrorOnBadPresenceTest(value bool) AttrFactoryOption {
	return canoninterpreter.EnableErrorOnBadPresenceTest(value)
}

func ExhaustiveEval() PlannerOption {
	return canoninterpreter.ExhaustiveEval()
}

func ExtendDispatcher(parent Dispatcher) Dispatcher {
	return canoninterpreter.ExtendDispatcher(parent)
}

func InterruptableEval() PlannerOption {
	return canoninterpreter.InterruptableEval()
}

func NewActivation(bindings any) (Activation, error) {
	return canoninterpreter.NewActivation(bindings)
}

func NewAttributeFactory(cont *containers.Container, a types.Adapter, p types.Provider, opts ...AttrFactoryOption) AttributeFactory {
	return canoninterpreter.NewAttributeFactory(cont, a, p, opts...)
}

func NewAttributePattern(variable string) *AttributePattern {
	return canoninterpreter.NewAttributePattern(variable)
}

func NewCall(id int64, function, overload string, args []InterpretableV2, impl functions.FunctionOp) InterpretableCall {
	return canoninterpreter.NewCall(id, function, overload, args, impl)
}

func NewConstValue(id int64, val ref.Val) InterpretableConst {
	return canoninterpreter.NewConstValue(id, val)
}

func NewCostTracker(estimator ActualCostEstimator, opts ...CostTrackerOption) (*CostTracker, error) {
	return canoninterpreter.NewCostTracker(estimator, opts...)
}

func NewDispatcher() Dispatcher {
	return canoninterpreter.NewDispatcher()
}

func NewEvalState() EvalState {
	return canoninterpreter.NewEvalState()
}

func NewExecutionFrame(input any) (*ExecutionFrame, error) {
	return canoninterpreter.NewExecutionFrame(input)
}

func NewHierarchicalActivation(parent Activation, child Activation) Activation {
	return canoninterpreter.NewHierarchicalActivation(parent, child)
}

func NewInterpreter(dispatcher Dispatcher,
	container *containers.Container,
	provider types.Provider,
	adapter types.Adapter,
	attrFactory AttributeFactory) Interpreter {
	return canoninterpreter.NewInterpreter(dispatcher, container, provider, adapter, attrFactory)
}

func NewPartialActivation(bindings any,
	unknowns ...*AttributePattern) (PartialActivation, error) {
	return canoninterpreter.NewPartialActivation(bindings, unknowns...)
}

func NewPartialAttributeFactory(container *containers.Container, adapter types.Adapter, provider types.Provider, opts ...AttrFactoryOption) AttributeFactory {
	return canoninterpreter.NewPartialAttributeFactory(container, adapter, provider, opts...)
}

func Optimize() PlannerOption {
	return canoninterpreter.Optimize()
}

func OverloadCostTracker(overloadID string, fnTracker FunctionTracker) CostTrackerOption {
	return canoninterpreter.OverloadCostTracker(overloadID, fnTracker)
}

func PresenceTestHasCost(hasCost bool) CostTrackerOption {
	return canoninterpreter.PresenceTestHasCost(hasCost)
}

func PruneAst(expr ast.Expr, macroCalls map[int64]ast.Expr, state EvalState) *ast.AST {
	return canoninterpreter.PruneAst(expr, macroCalls, state)
}

func RegexProgramSizeLimit(limit int) PlannerOption {
	return canoninterpreter.RegexProgramSizeLimit(limit)
}
