// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package containers

import (
	"cel.dev/cel-go/common/ast"
	canoncontainers "cel.dev/cel-go/common/containers"
)

// Type aliases
type (
	Container       = canoncontainers.Container
	ContainerOption = canoncontainers.ContainerOption
)

// Variables
var (
	DefaultContainer = canoncontainers.DefaultContainer
)

// Functions

func Abbrevs(qualifiedNames ...string) ContainerOption {
	return canoncontainers.Abbrevs(qualifiedNames...)
}

func Alias(qualifiedName, alias string) ContainerOption {
	return canoncontainers.Alias(qualifiedName, alias)
}

func Name(name string) ContainerOption {
	return canoncontainers.Name(name)
}

func NewContainer(opts ...ContainerOption) (*Container, error) {
	return canoncontainers.NewContainer(opts...)
}

func ToQualifiedName(e ast.Expr) (string, bool) {
	return canoncontainers.ToQualifiedName(e)
}
