// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package debug

import (
	"cel.dev/cel-go/common/ast"
	canondebug "cel.dev/cel-go/common/debug"
)

// Type aliases
type (
	Adorner = canondebug.Adorner
	Writer  = canondebug.Writer
)

// Functions

func ToAdornedDebugString(e ast.Expr, adorner Adorner) string {
	return canondebug.ToAdornedDebugString(e, adorner)
}

func ToDebugString(e ast.Expr) string {
	return canondebug.ToDebugString(e)
}

func ToDebugStringWithIDs(e ast.Expr) string {
	return canondebug.ToDebugStringWithIDs(e)
}
