// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package types

import (
	canontypes "cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/pb"
	"cel.dev/cel-go/common/types/ref"
	"cel.dev/cel-go/common/types/traits"
	celpb "cel.dev/expr"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/known/structpb"
	"reflect"
	"regexp"
	"time"
)

// Type aliases
type (
	Adapter                     = canontypes.Adapter
	AggregateSizeEstimate       = canontypes.AggregateSizeEstimate
	AggregateSizeVisitor        = canontypes.AggregateSizeVisitor
	AggregateSizer              = canontypes.AggregateSizer
	AttributeQualifier          = canontypes.AttributeQualifier
	AttributeTrail              = canontypes.AttributeTrail
	Bool                        = canontypes.Bool
	Bytes                       = canontypes.Bytes
	Double                      = canontypes.Double
	Duration                    = canontypes.Duration
	Err                         = canontypes.Err
	Error                       = canontypes.Error
	FieldType                   = canontypes.FieldType
	Int                         = canontypes.Int
	Kind                        = canontypes.Kind
	NativeType                  = canontypes.NativeType
	NativeTypeOption            = canontypes.NativeTypeOption
	NativeTypeOptions           = canontypes.NativeTypeOptions
	NativeTypesFieldNameHandler = canontypes.NativeTypesFieldNameHandler
	Null                        = canontypes.Null
	Optional                    = canontypes.Optional
	Provider                    = canontypes.Provider
	Registry                    = canontypes.Registry
	RegistryOption              = canontypes.RegistryOption
	SizeCalculator              = canontypes.SizeCalculator
	SizeCalculatorOption        = canontypes.SizeCalculatorOption
	String                      = canontypes.String
	StructTypeDescriptor        = canontypes.StructTypeDescriptor
	Timestamp                   = canontypes.Timestamp
	Type                        = canontypes.Type
	Uint                        = canontypes.Uint
	Unknown                     = canontypes.Unknown
)

// Constants
const (
	AnyKind         = canontypes.AnyKind
	BoolKind        = canontypes.BoolKind
	BytesKind       = canontypes.BytesKind
	DoubleKind      = canontypes.DoubleKind
	DurationKind    = canontypes.DurationKind
	DynKind         = canontypes.DynKind
	ErrorKind       = canontypes.ErrorKind
	False           = canontypes.False
	IntKind         = canontypes.IntKind
	IntNegOne       = canontypes.IntNegOne
	IntOne          = canontypes.IntOne
	IntZero         = canontypes.IntZero
	ListKind        = canontypes.ListKind
	MapKind         = canontypes.MapKind
	NullTypeKind    = canontypes.NullTypeKind
	OpaqueKind      = canontypes.OpaqueKind
	StringKind      = canontypes.StringKind
	StructKind      = canontypes.StructKind
	TimestampKind   = canontypes.TimestampKind
	True            = canontypes.True
	TypeKind        = canontypes.TypeKind
	TypeParamKind   = canontypes.TypeParamKind
	UintKind        = canontypes.UintKind
	UnknownKind     = canontypes.UnknownKind
	UnspecifiedKind = canontypes.UnspecifiedKind
)

// Variables
var (
	AnyType            = canontypes.AnyType
	BoolType           = canontypes.BoolType
	BytesType          = canontypes.BytesType
	DefaultTypeAdapter = canontypes.DefaultTypeAdapter
	DoubleType         = canontypes.DoubleType
	DurationType       = canontypes.DurationType
	DynType            = canontypes.DynType
	ErrType            = canontypes.ErrType
	ErrorType          = canontypes.ErrorType
	IntType            = canontypes.IntType
	IteratorType       = canontypes.IteratorType
	JSONListType       = canontypes.JSONListType
	JSONNullType       = canontypes.JSONNullType
	JSONStructType     = canontypes.JSONStructType
	JSONValueType      = canontypes.JSONValueType
	ListType           = canontypes.ListType
	MapType            = canontypes.MapType
	NullType           = canontypes.NullType
	NullValue          = canontypes.NullValue
	OptionalNone       = canontypes.OptionalNone
	OptionalType       = canontypes.OptionalType
	ProtoCELPrimitives = canontypes.ProtoCELPrimitives
	StringType         = canontypes.StringType
	TimestampType      = canontypes.TimestampType
	TypeType           = canontypes.TypeType
	UintType           = canontypes.UintType
	UnknownType        = canontypes.UnknownType
)

// Functions

func AlphaProtoAsType(t *exprpb.Type) (*Type, error) {
	return canontypes.AlphaProtoAsType(t)
}

func CompileRegexWithLimit(pattern string, limit int) (*regexp.Regexp, error) {
	return canontypes.CompileRegexWithLimit(pattern, limit)
}

func ComposeTypes(provider Provider, adapter Adapter, types ...any) (Provider, Adapter, error) {
	return canontypes.ComposeTypes(provider, adapter, types...)
}

func DurationGetHours(val ref.Val) ref.Val {
	return canontypes.DurationGetHours(val)
}

func DurationGetMilliseconds(val ref.Val) ref.Val {
	return canontypes.DurationGetMilliseconds(val)
}

func DurationGetMinutes(val ref.Val) ref.Val {
	return canontypes.DurationGetMinutes(val)
}

func DurationGetSeconds(val ref.Val) ref.Val {
	return canontypes.DurationGetSeconds(val)
}

func Equal(lhs ref.Val, rhs ref.Val) ref.Val {
	return canontypes.Equal(lhs, rhs)
}

func ExprTypeToType(t *exprpb.Type) (*Type, error) {
	return canontypes.ExprTypeToType(t)
}

func Format(val ref.Val) string {
	return canontypes.Format(val)
}

func IndexOrError(index ref.Val) (int, error) {
	return canontypes.IndexOrError(index)
}

func InsertMapKeyValue(m traits.Mapper, k, v ref.Val) ref.Val {
	return canontypes.InsertMapKeyValue(m, k, v)
}

func IsBool(elem ref.Val) bool {
	return canontypes.IsBool(elem)
}

func IsError(val ref.Val) bool {
	return canontypes.IsError(val)
}

func IsPrimitiveType(val ref.Val) bool {
	return canontypes.IsPrimitiveType(val)
}

func IsUnknown(val ref.Val) bool {
	return canontypes.IsUnknown(val)
}

func IsUnknownOrError(val ref.Val) bool {
	return canontypes.IsUnknownOrError(val)
}

func JSONFieldNames(enabled bool) RegistryOption {
	return canontypes.JSONFieldNames(enabled)
}

func LabelErrNode(id int64, val ref.Val) ref.Val {
	return canontypes.LabelErrNode(id, val)
}

func MaybeMergeUnknowns(val ref.Val, unk *Unknown) (*Unknown, bool) {
	return canontypes.MaybeMergeUnknowns(val, unk)
}

func MaybeNoSuchOverloadErr(val ref.Val) ref.Val {
	return canontypes.MaybeNoSuchOverloadErr(val)
}

func MergeUnknowns(unk1, unk2 *Unknown) *Unknown {
	return canontypes.MergeUnknowns(unk1, unk2)
}

func NewAttributeTrail(variable string) *AttributeTrail {
	return canontypes.NewAttributeTrail(variable)
}

func NewDynamicList(adapter Adapter, value any) traits.Lister {
	return canontypes.NewDynamicList(adapter, value)
}

func NewDynamicMap(adapter Adapter, value any) traits.Mapper {
	return canontypes.NewDynamicMap(adapter, value)
}

func NewEmptyRegistry() *Registry {
	return canontypes.NewEmptyRegistry()
}

func NewErr(format string, args ...any) ref.Val {
	return canontypes.NewErr(format, args...)
}

func NewErrFromString(message string) ref.Val {
	return canontypes.NewErrFromString(message)
}

func NewErrWithNodeID(id int64, format string, args ...any) ref.Val {
	return canontypes.NewErrWithNodeID(id, format, args...)
}

func NewJSONList(adapter Adapter, l *structpb.ListValue) traits.Lister {
	return canontypes.NewJSONList(adapter, l)
}

func NewJSONStruct(adapter Adapter, value *structpb.Struct) traits.Mapper {
	return canontypes.NewJSONStruct(adapter, value)
}

func NewListType(elemType *Type) *Type {
	return canontypes.NewListType(elemType)
}

func NewMapType(keyType, valueType *Type) *Type {
	return canontypes.NewMapType(keyType, valueType)
}

func NewMutableList(adapter Adapter) traits.MutableLister {
	return canontypes.NewMutableList(adapter)
}

func NewMutableMap(adapter Adapter, mutableValues map[ref.Val]ref.Val) traits.MutableMapper {
	return canontypes.NewMutableMap(adapter, mutableValues)
}

func NewNativeType(rawType reflect.Type, opts ...NativeTypeOption) (*NativeType, error) {
	return canontypes.NewNativeType(rawType, opts...)
}

func NewNullableType(wrapped *Type) *Type {
	return canontypes.NewNullableType(wrapped)
}

func NewObject(adapter Adapter,
	typeDesc *pb.TypeDescription,
	typeValue ref.Val,
	value proto.Message) ref.Val {
	return canontypes.NewObject(adapter, typeDesc, typeValue, value)
}

func NewObjectType(typeName string, traits ...int) *Type {
	return canontypes.NewObjectType(typeName, traits...)
}

func NewObjectTypeValue(typeName string) *Type {
	return canontypes.NewObjectTypeValue(typeName)
}

func NewOpaqueType(name string, params ...*Type) *Type {
	return canontypes.NewOpaqueType(name, params...)
}

func NewOptionalType(param *Type) *Type {
	return canontypes.NewOptionalType(param)
}

func NewProtoList(adapter Adapter, list protoreflect.List) traits.Lister {
	return canontypes.NewProtoList(adapter, list)
}

func NewProtoMap(adapter Adapter, value *pb.Map) traits.Mapper {
	return canontypes.NewProtoMap(adapter, value)
}

func NewProtoRegistry(opts ...RegistryOption) (*Registry, error) {
	return canontypes.NewProtoRegistry(opts...)
}

func NewRefValList(adapter Adapter, elems []ref.Val) traits.Lister {
	return canontypes.NewRefValList(adapter, elems)
}

func NewRefValMap(adapter Adapter, value map[ref.Val]ref.Val) traits.Mapper {
	return canontypes.NewRefValMap(adapter, value)
}

func NewRegistry(types ...any) (*Registry, error) {
	return canontypes.NewRegistry(types...)
}

func NewSizeCalculator(opts ...SizeCalculatorOption) *SizeCalculator {
	return canontypes.NewSizeCalculator(opts...)
}

func NewStringInterfaceMap(adapter Adapter, value map[string]any) traits.Mapper {
	return canontypes.NewStringInterfaceMap(adapter, value)
}

func NewStringList(adapter Adapter, elems []string) traits.Lister {
	return canontypes.NewStringList(adapter, elems)
}

func NewStringStringMap(adapter Adapter, value map[string]string) traits.Mapper {
	return canontypes.NewStringStringMap(adapter, value)
}

func NewTypeParamType(paramName string) *Type {
	return canontypes.NewTypeParamType(paramName)
}

func NewTypeTypeWithParam(param *Type) *Type {
	return canontypes.NewTypeTypeWithParam(param)
}

func NewTypeValue(typeName string, traits ...int) *Type {
	return canontypes.NewTypeValue(typeName, traits...)
}

func NewUnknown(id int64, attr *AttributeTrail) *Unknown {
	return canontypes.NewUnknown(id, attr)
}

func NoSuchOverloadErr() ref.Val {
	return canontypes.NoSuchOverloadErr()
}

func OptionalOf(value ref.Val) *Optional {
	return canontypes.OptionalOf(value)
}

func ParseStructField(handler NativeTypesFieldNameHandler) NativeTypeOption {
	return canontypes.ParseStructField(handler)
}

func ParseStructTag(tag string) NativeTypeOption {
	return canontypes.ParseStructTag(tag)
}

func ParseStructTags(enabled bool) NativeTypeOption {
	return canontypes.ParseStructTags(enabled)
}

func ParseTimestamp(val any) (time.Time, error) {
	return canontypes.ParseTimestamp(val)
}

func ProtoAsType(t *celpb.Type) (*Type, error) {
	return canontypes.ProtoAsType(t)
}

func ProtoTypeDefs(types ...proto.Message) RegistryOption {
	return canontypes.ProtoTypeDefs(types...)
}

func RegexProgramSize(pattern string) (int, error) {
	return canontypes.RegexProgramSize(pattern)
}

func SizeCalculatorMaxDepth(depth int) SizeCalculatorOption {
	return canontypes.SizeCalculatorMaxDepth(depth)
}

func SizeCalculatorMaxTraversal(traversal int) SizeCalculatorOption {
	return canontypes.SizeCalculatorMaxTraversal(traversal)
}

func SizeCalculatorStringUnitLength(length int) SizeCalculatorOption {
	return canontypes.SizeCalculatorStringUnitLength(length)
}

func StringContains(s, sub ref.Val) ref.Val {
	return canontypes.StringContains(s, sub)
}

func StringEndsWith(s, suf ref.Val) ref.Val {
	return canontypes.StringEndsWith(s, suf)
}

func StringStartsWith(s, pre ref.Val) ref.Val {
	return canontypes.StringStartsWith(s, pre)
}

func ToFoldableList(l traits.Lister) traits.Foldable {
	return canontypes.ToFoldableList(l)
}

func ToFoldableMap(m traits.Mapper) traits.Foldable {
	return canontypes.ToFoldableMap(m)
}

func TypeToExprType(t *Type) (*exprpb.Type, error) {
	return canontypes.TypeToExprType(t)
}

func TypeToProto(t *Type) (*celpb.Type, error) {
	return canontypes.TypeToProto(t)
}

func Types(types ...ref.Type) RegistryOption {
	return canontypes.Types(types...)
}

func UnsupportedRefValConversionErr(val any) ref.Val {
	return canontypes.UnsupportedRefValConversionErr(val)
}

func ValOrErr(val ref.Val, format string, args ...any) ref.Val {
	return canontypes.ValOrErr(val, format, args...)
}

func WrapErr(err error) ref.Val {
	return canontypes.WrapErr(err)
}
