load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

go_library(
    name = "go_default_library",
    srcs = ["alias.go"],
    importpath = "github.com/google/cel-go/common/types",
    deps = [
        "@dev_cel_cel_go//common/types:go_default_library",
        "@dev_cel_cel_go//common/types/pb:go_default_library",
        "@dev_cel_cel_go//common/types/ref:go_default_library",
        "@dev_cel_cel_go//common/types/traits:go_default_library",
        "@dev_cel_expr//:go_default_library",
        "@org_golang_google_genproto_googleapis_api//expr/v1alpha1:go_default_library",
        "@org_golang_google_protobuf//proto:go_default_library",
        "@org_golang_google_protobuf//reflect/protoreflect:go_default_library",
        "@org_golang_google_protobuf//types/known/structpb:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = ["alias_test.go"],
    deps = [
        ":go_default_library",
        "//common/types/ref:go_default_library",
        "//common/types/traits:go_default_library",
        "@dev_cel_cel_go//common/types:go_default_library",
        "@dev_cel_cel_go//common/types/ref:go_default_library",
        "@dev_cel_cel_go//common/types/traits:go_default_library",
    ],
)
