// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package overloads

import (
	canonoverloads "cel.dev/cel-go/common/overloads"
)

// Constants
const (
	AddBytes                             = canonoverloads.AddBytes
	AddDouble                            = canonoverloads.AddDouble
	AddDurationDuration                  = canonoverloads.AddDurationDuration
	AddDurationTimestamp                 = canonoverloads.AddDurationTimestamp
	AddInt64                             = canonoverloads.AddInt64
	AddList                              = canonoverloads.AddList
	AddString                            = canonoverloads.AddString
	AddTimestampDuration                 = canonoverloads.AddTimestampDuration
	AddUint64                            = canonoverloads.AddUint64
	BoolToBool                           = canonoverloads.BoolToBool
	BoolToString                         = canonoverloads.BoolToString
	BytesToBytes                         = canonoverloads.BytesToBytes
	BytesToString                        = canonoverloads.BytesToString
	Conditional                          = canonoverloads.Conditional
	Contains                             = canonoverloads.Contains
	ContainsString                       = canonoverloads.ContainsString
	DeprecatedIn                         = canonoverloads.DeprecatedIn
	DivideDouble                         = canonoverloads.DivideDouble
	DivideInt64                          = canonoverloads.DivideInt64
	DivideUint64                         = canonoverloads.DivideUint64
	DoubleToDouble                       = canonoverloads.DoubleToDouble
	DoubleToInt                          = canonoverloads.DoubleToInt
	DoubleToString                       = canonoverloads.DoubleToString
	DoubleToUint                         = canonoverloads.DoubleToUint
	DurationToDuration                   = canonoverloads.DurationToDuration
	DurationToHours                      = canonoverloads.DurationToHours
	DurationToInt                        = canonoverloads.DurationToInt
	DurationToMilliseconds               = canonoverloads.DurationToMilliseconds
	DurationToMinutes                    = canonoverloads.DurationToMinutes
	DurationToSeconds                    = canonoverloads.DurationToSeconds
	DurationToString                     = canonoverloads.DurationToString
	EndsWith                             = canonoverloads.EndsWith
	EndsWithString                       = canonoverloads.EndsWithString
	Equals                               = canonoverloads.Equals
	ExtFormatString                      = canonoverloads.ExtFormatString
	ExtQuoteString                       = canonoverloads.ExtQuoteString
	GreaterBool                          = canonoverloads.GreaterBool
	GreaterBytes                         = canonoverloads.GreaterBytes
	GreaterDouble                        = canonoverloads.GreaterDouble
	GreaterDoubleInt64                   = canonoverloads.GreaterDoubleInt64
	GreaterDoubleUint64                  = canonoverloads.GreaterDoubleUint64
	GreaterDuration                      = canonoverloads.GreaterDuration
	GreaterEqualsBool                    = canonoverloads.GreaterEqualsBool
	GreaterEqualsBytes                   = canonoverloads.GreaterEqualsBytes
	GreaterEqualsDouble                  = canonoverloads.GreaterEqualsDouble
	GreaterEqualsDoubleInt64             = canonoverloads.GreaterEqualsDoubleInt64
	GreaterEqualsDoubleUint64            = canonoverloads.GreaterEqualsDoubleUint64
	GreaterEqualsDuration                = canonoverloads.GreaterEqualsDuration
	GreaterEqualsInt64                   = canonoverloads.GreaterEqualsInt64
	GreaterEqualsInt64Double             = canonoverloads.GreaterEqualsInt64Double
	GreaterEqualsInt64Uint64             = canonoverloads.GreaterEqualsInt64Uint64
	GreaterEqualsString                  = canonoverloads.GreaterEqualsString
	GreaterEqualsTimestamp               = canonoverloads.GreaterEqualsTimestamp
	GreaterEqualsUint64                  = canonoverloads.GreaterEqualsUint64
	GreaterEqualsUint64Double            = canonoverloads.GreaterEqualsUint64Double
	GreaterEqualsUint64Int64             = canonoverloads.GreaterEqualsUint64Int64
	GreaterInt64                         = canonoverloads.GreaterInt64
	GreaterInt64Double                   = canonoverloads.GreaterInt64Double
	GreaterInt64Uint64                   = canonoverloads.GreaterInt64Uint64
	GreaterString                        = canonoverloads.GreaterString
	GreaterTimestamp                     = canonoverloads.GreaterTimestamp
	GreaterUint64                        = canonoverloads.GreaterUint64
	GreaterUint64Double                  = canonoverloads.GreaterUint64Double
	GreaterUint64Int64                   = canonoverloads.GreaterUint64Int64
	HasNext                              = canonoverloads.HasNext
	InList                               = canonoverloads.InList
	InMap                                = canonoverloads.InMap
	InMessage                            = canonoverloads.InMessage
	IndexList                            = canonoverloads.IndexList
	IndexMap                             = canonoverloads.IndexMap
	IndexMessage                         = canonoverloads.IndexMessage
	IntToDouble                          = canonoverloads.IntToDouble
	IntToInt                             = canonoverloads.IntToInt
	IntToString                          = canonoverloads.IntToString
	IntToTimestamp                       = canonoverloads.IntToTimestamp
	IntToUint                            = canonoverloads.IntToUint
	Iterator                             = canonoverloads.Iterator
	LessBool                             = canonoverloads.LessBool
	LessBytes                            = canonoverloads.LessBytes
	LessDouble                           = canonoverloads.LessDouble
	LessDoubleInt64                      = canonoverloads.LessDoubleInt64
	LessDoubleUint64                     = canonoverloads.LessDoubleUint64
	LessDuration                         = canonoverloads.LessDuration
	LessEqualsBool                       = canonoverloads.LessEqualsBool
	LessEqualsBytes                      = canonoverloads.LessEqualsBytes
	LessEqualsDouble                     = canonoverloads.LessEqualsDouble
	LessEqualsDoubleInt64                = canonoverloads.LessEqualsDoubleInt64
	LessEqualsDoubleUint64               = canonoverloads.LessEqualsDoubleUint64
	LessEqualsDuration                   = canonoverloads.LessEqualsDuration
	LessEqualsInt64                      = canonoverloads.LessEqualsInt64
	LessEqualsInt64Double                = canonoverloads.LessEqualsInt64Double
	LessEqualsInt64Uint64                = canonoverloads.LessEqualsInt64Uint64
	LessEqualsString                     = canonoverloads.LessEqualsString
	LessEqualsTimestamp                  = canonoverloads.LessEqualsTimestamp
	LessEqualsUint64                     = canonoverloads.LessEqualsUint64
	LessEqualsUint64Double               = canonoverloads.LessEqualsUint64Double
	LessEqualsUint64Int64                = canonoverloads.LessEqualsUint64Int64
	LessInt64                            = canonoverloads.LessInt64
	LessInt64Double                      = canonoverloads.LessInt64Double
	LessInt64Uint64                      = canonoverloads.LessInt64Uint64
	LessString                           = canonoverloads.LessString
	LessTimestamp                        = canonoverloads.LessTimestamp
	LessUint64                           = canonoverloads.LessUint64
	LessUint64Double                     = canonoverloads.LessUint64Double
	LessUint64Int64                      = canonoverloads.LessUint64Int64
	LogicalAnd                           = canonoverloads.LogicalAnd
	LogicalNot                           = canonoverloads.LogicalNot
	LogicalOr                            = canonoverloads.LogicalOr
	Matches                              = canonoverloads.Matches
	MatchesString                        = canonoverloads.MatchesString
	ModuloInt64                          = canonoverloads.ModuloInt64
	ModuloUint64                         = canonoverloads.ModuloUint64
	MultiplyDouble                       = canonoverloads.MultiplyDouble
	MultiplyInt64                        = canonoverloads.MultiplyInt64
	MultiplyUint64                       = canonoverloads.MultiplyUint64
	NegateDouble                         = canonoverloads.NegateDouble
	NegateInt64                          = canonoverloads.NegateInt64
	Next                                 = canonoverloads.Next
	NotEquals                            = canonoverloads.NotEquals
	NotStrictlyFalse                     = canonoverloads.NotStrictlyFalse
	Size                                 = canonoverloads.Size
	SizeBytes                            = canonoverloads.SizeBytes
	SizeBytesInst                        = canonoverloads.SizeBytesInst
	SizeList                             = canonoverloads.SizeList
	SizeListInst                         = canonoverloads.SizeListInst
	SizeMap                              = canonoverloads.SizeMap
	SizeMapInst                          = canonoverloads.SizeMapInst
	SizeString                           = canonoverloads.SizeString
	SizeStringInst                       = canonoverloads.SizeStringInst
	StartsWith                           = canonoverloads.StartsWith
	StartsWithString                     = canonoverloads.StartsWithString
	StringToBool                         = canonoverloads.StringToBool
	StringToBytes                        = canonoverloads.StringToBytes
	StringToDouble                       = canonoverloads.StringToDouble
	StringToDuration                     = canonoverloads.StringToDuration
	StringToInt                          = canonoverloads.StringToInt
	StringToString                       = canonoverloads.StringToString
	StringToTimestamp                    = canonoverloads.StringToTimestamp
	StringToUint                         = canonoverloads.StringToUint
	SubtractDouble                       = canonoverloads.SubtractDouble
	SubtractDurationDuration             = canonoverloads.SubtractDurationDuration
	SubtractInt64                        = canonoverloads.SubtractInt64
	SubtractTimestampDuration            = canonoverloads.SubtractTimestampDuration
	SubtractTimestampTimestamp           = canonoverloads.SubtractTimestampTimestamp
	SubtractUint64                       = canonoverloads.SubtractUint64
	TimeGetDate                          = canonoverloads.TimeGetDate
	TimeGetDayOfMonth                    = canonoverloads.TimeGetDayOfMonth
	TimeGetDayOfWeek                     = canonoverloads.TimeGetDayOfWeek
	TimeGetDayOfYear                     = canonoverloads.TimeGetDayOfYear
	TimeGetFullYear                      = canonoverloads.TimeGetFullYear
	TimeGetHours                         = canonoverloads.TimeGetHours
	TimeGetMilliseconds                  = canonoverloads.TimeGetMilliseconds
	TimeGetMinutes                       = canonoverloads.TimeGetMinutes
	TimeGetMonth                         = canonoverloads.TimeGetMonth
	TimeGetSeconds                       = canonoverloads.TimeGetSeconds
	TimestampToDayOfMonthOneBased        = canonoverloads.TimestampToDayOfMonthOneBased
	TimestampToDayOfMonthOneBasedWithTz  = canonoverloads.TimestampToDayOfMonthOneBasedWithTz
	TimestampToDayOfMonthZeroBased       = canonoverloads.TimestampToDayOfMonthZeroBased
	TimestampToDayOfMonthZeroBasedWithTz = canonoverloads.TimestampToDayOfMonthZeroBasedWithTz
	TimestampToDayOfWeek                 = canonoverloads.TimestampToDayOfWeek
	TimestampToDayOfWeekWithTz           = canonoverloads.TimestampToDayOfWeekWithTz
	TimestampToDayOfYear                 = canonoverloads.TimestampToDayOfYear
	TimestampToDayOfYearWithTz           = canonoverloads.TimestampToDayOfYearWithTz
	TimestampToHours                     = canonoverloads.TimestampToHours
	TimestampToHoursWithTz               = canonoverloads.TimestampToHoursWithTz
	TimestampToInt                       = canonoverloads.TimestampToInt
	TimestampToMilliseconds              = canonoverloads.TimestampToMilliseconds
	TimestampToMillisecondsWithTz        = canonoverloads.TimestampToMillisecondsWithTz
	TimestampToMinutes                   = canonoverloads.TimestampToMinutes
	TimestampToMinutesWithTz             = canonoverloads.TimestampToMinutesWithTz
	TimestampToMonth                     = canonoverloads.TimestampToMonth
	TimestampToMonthWithTz               = canonoverloads.TimestampToMonthWithTz
	TimestampToSeconds                   = canonoverloads.TimestampToSeconds
	TimestampToSecondsWithTz             = canonoverloads.TimestampToSecondsWithTz
	TimestampToString                    = canonoverloads.TimestampToString
	TimestampToTimestamp                 = canonoverloads.TimestampToTimestamp
	TimestampToYear                      = canonoverloads.TimestampToYear
	TimestampToYearWithTz                = canonoverloads.TimestampToYearWithTz
	ToDyn                                = canonoverloads.ToDyn
	TypeConvertBool                      = canonoverloads.TypeConvertBool
	TypeConvertBytes                     = canonoverloads.TypeConvertBytes
	TypeConvertDouble                    = canonoverloads.TypeConvertDouble
	TypeConvertDuration                  = canonoverloads.TypeConvertDuration
	TypeConvertDyn                       = canonoverloads.TypeConvertDyn
	TypeConvertInt                       = canonoverloads.TypeConvertInt
	TypeConvertString                    = canonoverloads.TypeConvertString
	TypeConvertTimestamp                 = canonoverloads.TypeConvertTimestamp
	TypeConvertType                      = canonoverloads.TypeConvertType
	TypeConvertUint                      = canonoverloads.TypeConvertUint
	UintToDouble                         = canonoverloads.UintToDouble
	UintToInt                            = canonoverloads.UintToInt
	UintToString                         = canonoverloads.UintToString
	UintToUint                           = canonoverloads.UintToUint
)

// Functions

func IsTypeConversionFunction(function string) bool {
	return canonoverloads.IsTypeConversionFunction(function)
}
