// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cel-go compatibility generator. DO NOT EDIT.

package checker

import (
	canonchecker "cel.dev/cel-go/checker"
	"cel.dev/cel-go/common"
	"cel.dev/cel-go/common/ast"
	"cel.dev/cel-go/common/containers"
	"cel.dev/cel-go/common/types"
	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

// Type aliases
type (
	AstNode           = canonchecker.AstNode
	CallEstimate      = canonchecker.CallEstimate
	CostEstimate      = canonchecker.CostEstimate
	CostEstimator     = canonchecker.CostEstimator
	CostOption        = canonchecker.CostOption
	Env               = canonchecker.Env
	FunctionEstimator = canonchecker.FunctionEstimator
	Group             = canonchecker.Group
	Option            = canonchecker.Option
	Scopes            = canonchecker.Scopes
	SizeEstimate      = canonchecker.SizeEstimate
)

// Functions

func Check(parsed *ast.AST, source common.Source, env *Env) (*ast.AST, *common.Errors) {
	return canonchecker.Check(parsed, source, env)
}

func Cost(checked *ast.AST, estimator CostEstimator, opts ...CostOption) (CostEstimate, error) {
	return canonchecker.Cost(checked, estimator, opts...)
}

func CrossTypeNumericComparisons(enabled bool) Option {
	return canonchecker.CrossTypeNumericComparisons(enabled)
}

func FixedCostEstimate(fixedCost uint64) CostEstimate {
	return canonchecker.FixedCostEstimate(fixedCost)
}

func FixedSizeEstimate(size uint64) SizeEstimate {
	return canonchecker.FixedSizeEstimate(size)
}

func FormatCELType(t any) string {
	return canonchecker.FormatCELType(t)
}

func FormatCheckedType(t *exprpb.Type) string {
	return canonchecker.FormatCheckedType(t)
}

func JSONFieldNames(enabled bool) Option {
	return canonchecker.JSONFieldNames(enabled)
}

func NewEnv(container *containers.Container, provider types.Provider, opts ...Option) (*Env, error) {
	return canonchecker.NewEnv(container, provider, opts...)
}

func OverloadCostEstimate(overloadID string, functionCoster FunctionEstimator) CostOption {
	return canonchecker.OverloadCostEstimate(overloadID, functionCoster)
}

func PresenceTestHasCost(hasCost bool) CostOption {
	return canonchecker.PresenceTestHasCost(hasCost)
}

func Print(e ast.Expr, checked *ast.AST) string {
	return canonchecker.Print(e, checked)
}

func UnknownCostEstimate() CostEstimate {
	return canonchecker.UnknownCostEstimate()
}

func UnknownSizeEstimate() SizeEstimate {
	return canonchecker.UnknownSizeEstimate()
}

func ValidatedDeclarations(env *Env) Option {
	return canonchecker.ValidatedDeclarations(env)
}
